### ISSUE TITLE
WSS and SSL certificate issues in Android

### ISSUE THREAD

**Issue by sandeep-webonise** [crossbario/autobahn-java#105]
I am trying to connect to a websocket having wss protocol. I tried the AutoBahn library and able to connect to wss://echo.websocket.org but when I am trying to connect to our server, I am getting 403 (Forbidden) error. We have our own SSL certificate provided by GoDaddy. The socket connection works perfectly fine from iOS devices and browsers but not on Android.

I have also tried bypassing the SSL certificates and creating my own.

As it's security related, can't put the wss link of our server here.

```
10-20 14:03:53.831 16402-16402/com.cameronpalmer.echo D/de.tavendo.autobahn.WebSocketConnection: WebSocket connection created.
10-20 14:03:54.107 16402-16402/com.cameronpalmer.echo D/de.tavendo.autobahn.WebSocketReader: WebSocket reader created.
10-20 14:03:54.109 16402-16402/com.cameronpalmer.echo D/de.tavendo.autobahn.WebSocketConnection: WebSocket reader created and started.
10-20 14:03:54.114 16402-16402/com.cameronpalmer.echo D/de.tavendo.autobahn.WebSocketWriter: WebSocket writer created.
10-20 14:03:56.153 16402-16617/com.cameronpalmer.echo D/de.tavendo.autobahn.WebSocketReader: WebSocker reader running.
10-20 14:03:56.158 16402-16618/com.cameronpalmer.echo D/de.tavendo.autobahn.WebSocketWriter: WebSocker writer running.
10-20 14:03:56.158 16402-16402/com.cameronpalmer.echo D/de.tavendo.autobahn.WebSocketConnection: WebSocket writer created and started.
10-20 14:03:56.165 16402-16402/com.cameronpalmer.echo W/Performance: More than 500 ms to handle , msg.target = Handler (android.view.ViewRootImpl$ViewRootHandler) {c6fab6} , msg.callback = android.view.View$PerformClick@3e063b7, msg.what = 0 , takenTime = 2338 , startTime = 408345922
10-20 14:03:56.167 16402-16402/com.cameronpalmer.echo I/Choreographer: Skipped 140 frames!  The application may be doing too much work on its main thread.
10-20 14:03:56.466 16402-16617/com.cameronpalmer.echo W/de.tavendo.autobahn.WebSocketReader: Status: 403 (Forbidden)
10-20 14:03:56.467 16402-16617/com.cameronpalmer.echo D/de.tavendo.autobahn.WebSocketReader: WebSocket reader ended.
10-20 14:03:56.467 16402-16402/com.cameronpalmer.echo D/de.tavendo.autobahn.WebSocketConnection: fail connection [code = SERVER_ERROR, reason = Server error 403 (Forbidden)
10-20 14:03:56.467 16402-16402/com.cameronpalmer.echo D/de.tavendo.autobahn.WebSocketReader: quit
10-20 14:03:56.468 16402-16618/com.cameronpalmer.echo D/de.tavendo.autobahn.WebSocketWriter: WebSocket writer ended.
10-20 14:03:56.470 16402-16402/com.cameronpalmer.echo D/com.cameronpalmer.echo.EchoActivity: Close: SERVER_ERROR, Server error 403 (Forbidden)
10-20 14:03:56.471 16402-16402/com.cameronpalmer.echo D/de.tavendo.autobahn.WebSocketConnection: worker threads stopped
10-20 14:03:56.471 16402-16402/com.cameronpalmer.echo D/de.tavendo.autobahn.WebSocketConnection: opening handshake received
10-20 14:03:56.471 16402-16611/com.cameronpalmer.echo D/de.tavendo.autobahn.WebSocketConnection: SocketThread exited.
```

**Comment by ShanZha** [comment]
Do you have been solved?

**Comment by jeganumapathy** [comment]
Hi 

Does any one solved the issue.

**Comment by oberstet** [comment]
We have started basically a complete rewrite of AutobahnAndroid (incubated on branch https://github.com/crossbario/autobahn-java/tree/abjv2), so this PR/issue does not apply anymore.

The rewrite will add full support for both TLS and WAMPv2. It will run on both Android and plain Java 8 (client). The user API for WAMP will be based on `CompletableFuture` (no callback hell anymore).

**Comment by sandeep-webonise** [comment]
@oberstet - Thanks for the response. Can you tell me what is the expected time or when the basic version will be available. I would like to try and see if it works for me. Being said that, I really appreciate that you guys work so hard to release libraries like this to make our life easier.

**Comment by oberstet** [comment]
@sandeep-webonise all development is done by @om23er https://github.com/om26er, and he is working hard to make it happen "soon". Help with testing etc is definitely highly welcome!

> Me I am only involved in guidance/design .. so best nag him;) I guess NIO is ripped out already, and next is TLS ..
