### ISSUE TITLE
Support for marshmallow?

### ISSUE THREAD

**Issue by jojonarte** [crossbario/autobahn-java#106]

**Comment by liraz** [comment]
Getting the following exception on a 7.1.1 nexus 5x device:
```
Fatal Exception: java.nio.channels.IllegalBlockingModeException
       at sun.nio.ch.SocketAdaptor.connect(SocketAdaptor.java:94)
       at de.tavendo.autobahn.WebSocketConnection$WebSocketConnector.run(WebSocketConnection.java:79)
```

Lock the screen, wait a little bit, then unlock - it crashes.

**Comment by oberstet** [comment]
The new rewrite currently being under development does not use NIO (`java.nio.*`) at all, so this won't apply any longer. Help with testing of the new rewrite would be welcome though!
