### ISSUE TITLE
secure WebSockets not implemented

### ISSUE THREAD

**Issue by Jianglei0716** [crossbario/autobahn-java#108]
how can i connect with wss？

**Comment by oberstet** [comment]
We have started basically a complete rewrite of AutobahnAndroid (incubated on branch https://github.com/crossbario/autobahn-java/tree/abjv2), so this PR/issue does not apply anymore.

The rewrite will add full support for both TLS and WAMPv2. It will run on both Android and plain Java 8 (client). The user API for WAMP will be based on `CompletableFuture` (no callback hell anymore).
