### ISSUE TITLE
JSON payload handler

### ISSUE THREAD

**Issue by pkyad** [crossbario/autobahn-java#109]
Is there a json payload handler that i can override. I looked around and did not see anything. On the other hand what is the case when we try to connect WAMP2 application with the lib which is based on WAMP1, will that json payload from (say AutobahnJS) will be received as string ?

**Comment by oberstet** [comment]
We have started basically a complete rewrite of AutobahnAndroid (incubated on branch https://github.com/crossbario/autobahn-java/tree/abjv2), so this PR/issue does not apply anymore.

The rewrite will add full support for both TLS and WAMPv2. It will run on both Android and plain Java 8 (client). The user API for WAMP will be based on `CompletableFuture` (no callback hell anymore).
