### ISSUE TITLE
PubSub get more information from event

### ISSUE THREAD

**Issue by anboo** [crossbario/autobahn-java#111]
https://github.com/crossbario/autobahn-android/blob/master/Demo/SimplePubSub/src/de/tavendo/autobahn/simplepubsub/SimplePubSubActivity.java

How I can get any information from event? WS server sending me more than just num,name,flag,created,rand?
If I add custom properties for Event class this will be throw Serialization error for me.

> W/System.err: org.codehaus.jackson.map.JsonMappingException: Can not deserialize instance of java.lang.String out of START_OBJECT token

**Comment by oberstet** [comment]
We have started basically a complete rewrite of AutobahnAndroid (incubated on branch https://github.com/crossbario/autobahn-java/tree/abjv2), so this PR/issue does not apply anymore.

The rewrite will add full support for both TLS and WAMPv2. It will run on both Android and plain Java 8 (client). The user API for WAMP will be based on `CompletableFuture` (no callback hell anymore).
