### ISSUE TITLE
Can't connect to websocket - Chrome App

### ISSUE THREAD

**Issue by caffaware** [crossbario/autobahn-java#112]
Hi, 

I've made a chrome app which uses this https://github.com/GoogleChrome/chrome-app-samples/blob/master/samples/websocket-server/index.js implementation for setting up a websocket server. I can't connect to this one with my Android app, I always get: "D/de.tavendo.autobahn.WebSocketConnection: fail connection [code = 3, reason = WebSockets connection lost" 

However, when I setup a websocket connection using nodejs, connection works perfectly, any ideas ?

**Comment by oberstet** [comment]
We have started basically a complete rewrite of AutobahnAndroid (incubated on branch https://github.com/crossbario/autobahn-java/tree/abjv2), so this PR/issue does not apply anymore.

The rewrite will add full support for both TLS and WAMPv2. It will run on both Android and plain Java 8 (client). The user API for WAMP will be based on `CompletableFuture` (no callback hell anymore).
