### ISSUE TITLE
Server not receiving all headers I'm sending

### ISSUE THREAD

**Issue by KoderKrishanu** [crossbario/autobahn-java#113]
Following is my code. On the server, I'm getting `authorization` in header but not the `devicetype` header  

        String wsuri = "ws://" + host;
        String[] protocols = {};
        List<BasicNameValuePair> headers = new ArrayList<>();
        String auth = username + ":" + Settings.Secure.getString(getContentResolver(), Settings.Secure.ANDROID_ID);
        headers.add(new BasicNameValuePair("authorization", getAuth());
        headers.add(new BasicNameValuePair("devicetype", "android"));
        try {
            mConnection.connect(wsuri, protocols, new WebSocket.ConnectionHandler() {
                @Override
                public void onOpen() {
                    Log.d("WebSocket", "Connected");
                }

                @Override
                public void onClose(int code, String reason) {
                    Log.d("WebSocket", "Connection lost");
                }

                @Override
                public void onTextMessage(String payload) {
                    Log.d("WebSocket", payload);
                }

                @Override
                public void onRawTextMessage(byte[] payload) {
                    Log.d("WebSocket", "onRawTextMessage.");
                }

                @Override
                public void onBinaryMessage(byte[] payload) {
                    Log.d("WebSocket", "onBinaryMessage.");

                }
            }, new WebSocketOptions(), headers);
        } catch (WebSocketException e) {
            Log.d("WebSocket", e.toString());
        }

**Comment by oberstet** [comment]
We have started basically a complete rewrite of AutobahnAndroid (incubated on branch https://github.com/crossbario/autobahn-java/tree/abjv2), so this PR/issue does not apply anymore.

The rewrite will add full support for both TLS and WAMPv2. It will run on both Android and plain Java 8 (client). The user API for WAMP will be based on `CompletableFuture` (no callback hell anymore).
