### ISSUE TITLE
Stop using NIO

### ISSUE THREAD

**Issue by om26er** [crossbario/autobahn-java#114]
We need to move away from NIO and start using plain Socket. While doing that, lets implement TLS as well.

This is one phase of https://github.com/crossbario/autobahn-android/issues/92

**Comment by om26er** [comment]
ugh, apparently, I can't assign this issue to myself.

**Comment by oberstet** [comment]
I believe this is finally done. NIO is gone, and the library should run on TLS @om26er hooray=) Great job!
