### ISSUE TITLE
Remove build artifacts/tools

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-java#124]
Which of the following are actually required? Everything not should be removed from the repo (definitely the JARs, and definitely the Windows BAT):

```
-rw-rw-r--  1 oberstet oberstet   201 Mai 14 14:42 build.gradle
drwxrwxr-x  3 oberstet oberstet  4096 Mai 14 14:42 gradle/
-rwxrwxr-x  1 oberstet oberstet  4971 Mai 14 14:42 gradlew*
-rw-rw-r--  1 oberstet oberstet  2404 Mai 14 14:42 gradlew.bat
-rw-rw-r--  1 oberstet oberstet    37 Mai 14 14:42 settings.gradle
```

**Comment by om26er** [comment]
The two *.gradle files are required by the project to actually build. I created a [pull request](https://github.com/crossbario/autobahn-java/pull/130) that removes the gradle wrapper, that was used to install it. Our recommended way will be Docker.

**Comment by oberstet** [comment]
fixed on abjv2 branch
