### ISSUE TITLE
Auto generate docs

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-java#126]
I have no clue if there currently is a preferred way in the Java and/or Android communities regarding hosting docs.

In Python, there is [RTD](https://readthedocs.org/), and this pretty much standard. A good citizen Python library will have its docs on RTD. Eg here is [AutobahnPython docs](http://autobahn.readthedocs.io/en/latest/).

---

For C++, there is no such thing, and hence we do the following:

* generate docs from source code using Doxygen
* put the generated docs into a dedicated repo https://github.com/crossbario/autobahn-cpp-docs
* activate GH pages, so above repo is hosted automatically https://crossbario.github.io/autobahn-cpp-docs/

---

If we don't come up with a better idea, I'd do exactly the same for ABJ.

**Comment by oberstet** [comment]
@om26er so as we don't have a lot here, this issue is more about deciding what code documentation flavor we actually want to use, maybe document a couple of core things, and thats it. so, what flavor?

**Comment by oberstet** [comment]
obviously, the public user API doc strings for functions on WAMP session etc would be nice to have documented. if we had that at least, then the hosting of the docs would make sense too. otherwise the other issue with the docs hosting questions becomes secondary too.

**Comment by om26er** [comment]
@oberstet So where shall the document be hosted, we probably want to host them somethere that's linked to crossbar.io (website)

**Comment by om26er** [comment]
Currently I have them hosted on a digitalocean droplet: http://138.68.132.252:8000/

**Comment by oberstet** [comment]
@om26er I have sketched 2 options for hosting here: https://github.com/crossbario/autobahn-java/issues/168
