### ISSUE TITLE
WebSocket Testsuite runs 100% green

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-java#138]
We should have a 100% green run on the AB testsuite for AB Java - other than the WebSocket compression tests that is.

**Comment by oberstet** [comment]
Actually, now that it is clear how to run multiple Docker containers in Travis CI runs, we could run the Autobahn testsuite in a first container (in fuzzing server mode), and then run the test client (ABJ) in a second container.

This way, we could have the testsuite run automatically.

However, this depends on the whole Android SDK being available from within Travis CI, and this seems to violate the usage and/or license terms of the Android SDK.

And for WAMP testing, the above testsuite is of no use. Mmh. Lets postpone this issue.

**Comment by om26er** [comment]
I think we are now at a "good enough" stage with WebSocket tests after the recent performance improvements.
