### ISSUE TITLE
Document main usage idioms

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-java#147]
Example demonstrating usage with different types of args/kwargs in call and publish arguments, call returns and call errors, etc

- Use of Jackson data-binding (to/from POJOs)
- Use of JDK Lists and Maps over POJOs

**Comment by oberstet** [comment]
The example serves multiple purposes:

* documentation (for users)
* copy-paste collection (for users to steal from in their code)
* build & test purposes (for us)

**Comment by om26er** [comment]
The initial set of examples what cover POJO cases like [here](https://github.com/crossbario/autobahn-java/blob/master/demo-gallery/src/main/java/io/crossbar/autobahn/demogallery/POJOCallExamples.java) and [here](https://github.com/crossbario/autobahn-java/blob/master/demo-gallery/src/main/java/io/crossbar/autobahn/demogallery/POJORegisterExamples.java).

**Comment by om26er** [comment]
I think we can actually provide "better" examples once we write an App that uses ABJ. That way we will be covering some (assuming) difficult scenarios, we will also be able to then document some "best practices" and "what not to do" kind of scenarios.

**Comment by oberstet** [comment]
where have all the code examples from https://github.com/crossbario/autobahn-java/blob/058f3718cdd779b1d728d2696259471d5f508e78/demo-gallery/src/main/java/io/crossbar/autobahn/demogallery/netty/Service.java gone?

eg `class Person`?

Please readd all that code to the example.

**Comment by oberstet** [comment]
ah, sorry! I see: the class has been split out. so https://github.com/crossbario/autobahn-java/blob/master/demo-gallery/src/main/java/io/crossbar/autobahn/demogallery/netty/Service.java still has all the examples that were in above `Service.java`?

how does a user find those examples?

I think it would be good to have those snippets of regular usage in the README.md, eg:

"Here is how to call a remote procedure that returns a list of `Person` POJOs":

```java
// call a remote procedure that returns a List<Person>
List<Object> args = new ArrayList<>();
args.add("department-7");

CompletableFuture<List<Person>> future = mSession.call("com.example.get_persons_by_department",
        args, new TypeReference<List<Person>>() {});

future.whenCompleteAsync((persons, throwable) -> {
    if (throwable != null) {
        // handle error
    } else {
        // success!
        for (Person person: persons) {
            // do something with person
        }
    }
}, mExecutor);
```

**Comment by oberstet** [comment]
As this is basically a doc issue, I adjusted the labels ..

**Comment by oberstet** [comment]
Where are the other idioms?

**Comment by oberstet** [comment]
Well, maybe add doc snippets over time .. on the go .. and close this one for now, and we can ship a release.

**Comment by om26er** [comment]
Thanks and sorry for being sloppy on that one. I think I'll have better examples while I work on an Android app using ABJ (which we are working on).
