### ISSUE TITLE
io.crossbar.autobahn.wamp Error:(122, 28) error: <identifier> expected

### ISSUE THREAD

**Issue by AnthonyKoueik** [crossbario/autobahn-java#150]
I am getting these errors when building the project 

`C:\Users\koa\Desktop\My Apps\autobahn-java\autobahn\src\main\java\io\crossbar\autobahn\Wamp.java
Error:(122, 28) error: <identifier> expected
Error:(122, 36) error: <identifier> expected
Error:(122, 45) error: <identifier> expected
Error:(122, 46) error: ';' expected
Error:(124, 21) error: illegal start of type
Error:(124, 22) error: ')' expected
Error:(124, 26) error: ';' expected
Error:(124, 34) error: <identifier> expected
Error:(124, 35) error: ';' expected
Error:(124, 43) error: illegal start of type
Error:(124, 44) error: <identifier> expected
Error:(124, 48) error: = expected
Error:(147, 27) error: illegal start of type
Error:(147, 28) error: ')' expected
Error:(148, 2) error: ';' expected
Error:(167, 12) error: illegal start of type
Error:(167, 13) error: ';' expected
Error:(167, 14) error: illegal start of type
Error:(168, 12) error: illegal start of type
Error:(168, 13) error: ';' expected
Error:(168, 22) error: <identifier> expected
Error:(271, 2) error: reached end of file while parsing
Error:Execution failed for task ':autobahn:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
Information:BUILD FAILED
Information:Total time: 1.553 secs
Information:23 errors
Information:0 warnings
Information:See complete output in console`

**Comment by om26er** [comment]
Hi! Please pull from master again, the codepath that you are hitting no longer exists.

**Comment by om26er** [comment]
oh, please ignore my last comment. You need to comment out that Wamp.java file for your project to compile. That file only has pseudo code for illustration purposes.

**Comment by AnthonyKoueik** [comment]
sorry for my late reply,  i will do it. thanks

**Comment by oberstet** [comment]
This specific file is under development (the WAMP support layer). Just exclude from your project file.
