### ISSUE TITLE
Publish on Maven

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-java#16]
To get the AutobahnAndroid artifact into the maven central repository you should use the facilities offered by oss.sonatype.org.
https://docs.sonatype.org/display/Repository/Sonatype+OSS+Maven+Repository+Usage+Guide

That should help you understand how to get the artifact and all associated metadata up to oss.sonatype.org, once you are happy with it, you can request that your artifacts be synced to Maven Central http://repo.maven.org/

FYI, sonatype.org is run by many Apache Maven committer and PMC members, they do a great job in helping out the open source community.

**Comment by bjenning04** [comment]
+1, would really like to be able to pull this into my team's Android Gradle project through Maven.

**Comment by disciple97** [comment]
+1, really appreciate it.

**Comment by vach** [comment]
+1,  adding jars in classpath sucks

**Comment by pielambr** [comment]
+1, would be really nice

**Comment by pielambr** [comment]
+1, would be nice for use with Gradle

**Comment by mars3142** [comment]
I found a new service, which creates maven/gradle usage on the fly from git-hashes or github release tags: https://jitpack.io/#tavendo/AutobahnAndroid/v0.5.2

**Comment by rene-dohan** [comment]
mars3142 cool , this works , is there some drawbacks? like slower build time or something ?

**Comment by mars3142** [comment]
Don't know. The tool isn't from me. Just contact the creator: jitpack@jitpack.io ;)

**Comment by James-Firth** [comment]
+1 would also like to have this available for use with gradle

**Comment by abcdeiko** [comment]
mars3142, don't use Autobahn from jitpack.io, it uses wrong old version.
This is my post on SO http://stackoverflow.com/a/30777724/3363782

**Comment by oberstet** [comment]
Sorry guys, I long left Java/Android .. I have no idea what's the latest rage in Java package hosting / distribution.

Is it Maven, jitpack, whatnot?

But I agree: whatever the current preferred hosting for Android devs is, we should support that.

I am leaving this open .. it should be addressed as part of https://github.com/crossbario/autobahn-android/issues/92

**Comment by rene-dohan** [comment]
Well jitpack is workaround when it is not on maven ? maven is standard , nothing new here ... just support maven properly !

**Comment by oberstet** [comment]
@rene-dohan alright. then Maven. sorry for confusion, I am not following things in the Java world closely ..

**Comment by Muyangmin** [comment]
@oberstet MavenCentral is a good choice, either [jcenter](https://bintray.com/). Btw, jcenter is the default repository for android projects now.

**Comment by jgamedev** [comment]
I see that 0.5.2 is now available thru jitpack:  https://jitpack.io/#crossbario/autobahn-android
I'll just say for me personally it sucks to be late to the websocket party and not know what ppl are using for Android.

**Comment by zjulia** [comment]
Have there been any updates on this issue?

**Comment by brunocvcunha** [comment]
Any updates?

**Comment by om26er** [comment]
> Any updates?

We are working on this, I'll try to get a test version uploaded to a central repo this week.

**Comment by oberstet** [comment]
@om26er the groupId for the project has been created https://issues.sonatype.org/browse/OSSRH-34508

**Comment by oberstet** [comment]
@all interested in this: ok, we have the `groupId` on sonatype. now, actually uploading a bunch of jars seems to be ridiculously complicated https://docs.gradle.org/current/userguide/publishing_maven.html

what we would like to have is a target in the `Makefile` like `publish_maven` that uploads JARs left in a local directory to maven.

anyone with active knowledge in this stuff who could help out?

**Comment by jintux** [comment]
I know about maven and I know about cmake. What can I do you for?

**Comment by jintux** [comment]
Hi oberstet, I have experience in both so I will try to help.

**Comment by jintux** [comment]
Hi Oberstet, here is a step by step guide to follow for your case: http://central.sonatype.org/pages/gradle.html
If you need any assistance let me know.

**Comment by om26er** [comment]
The library will be published under io.crossbar.autobahn group with multiple sub packages, namely:

1. autobahn-android
2. autobahn-java(or -netty)

So for consumers the "import" line in their build.gralde look like
```
implementation 'io.crossbar.autobahn:autobahn-android:17.X.X'
```

Given Android studio defaults to JCenter() as its default repository, I suggest that we should take the generic approach here i.e: Upload to Bintray and from there Sync to both JCenter and Maven Central. That will give us a streamlined workflow.

**Comment by om26er** [comment]
Autobahn is now published to JCenter, we'll sync to Maven Central from there.

**Comment by om26er** [comment]
We are now on both JCenter and Maven. http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22io.crossbar.autobahn%22
