### ISSUE TITLE
Implement all WAMP message classes

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-java#162]
The class `io.crossbar.autobahn.wamp.types.Hello` already is (almost) finished and can serve as a template for implementing all the other `Message` classes.

Only thing: I think it would be good to move the respective source files to `io.crossbar.wamp.message` namespace (into a new folder /src/main/java/io/crossbar/autobahn/wamp/message/). Reason: there are dozens of message classes needed (actually, the sum of code lines in these Message classes will be a large chunk of the whole library), and to keep them nicely together/separated ..

**Comment by darkl** [comment]
Hi Tobias,
Once you finish the Hello class, I can help trying to automatically generate these classes using my [meta-wamp](https://github.com/darkl/meta-wamp) project.
Please look at the metadata provided there and see if it suites you.

Elad

**Comment by oberstet** [comment]
@darkl Hi Elad, cool, wasn't aware of this  project! So the idea is to read the JSON files, put that into some kind of code generator and spill out Java source files?

I do think this could have some long-term benefits - and it could come in handy if we start on the planned AutobahnC in particular. Will keep that in mind. Right now, and for AutobahnJava, we are probably quicker writing the code manually - thing is, we need to meet a deadline on this which is quite soon .. bringing in another build step, writing a generator etc ..

**Comment by darkl** [comment]
Yeah, that's the idea. Thanks for considering it :)

**Comment by oberstet** [comment]
@darkl For an AutobahnC, I am wondering if putting the JSON definitions from meta-wamp through two Jinja2 templates to generate a C header and a C impl file for each WAMP Message "class" (whatever the C struct we come up with for a WAMP message in C). Much like they do here https://www.chromium.org/developers/jinja

What do you think?

**Comment by oberstet** [comment]
Could be useful also, because it could allow us to integrate with the serializer code in C very efficiently as well.

**Comment by darkl** [comment]
Cool! I never heard of Jinja, looks awesome.

Yeah, that's kind of the idea. My only experience in this was with some ad-hoc ugly scripts in C# that I wrote and played with. You can see the generated code here: [#1](https://github.com/darkl/wamp-ts/blob/master/src/wamp-ts/Core/Contracts.ts), [#2](https://github.com/darkl/autobahn-android/blob/b2d3cbcc1160dd60d053f0b5affb44df2259598d/Autobahn/src/de/tavendo/autobahn/WampMessage.java), [#3](https://github.com/firebug/websocket-monitor/blob/master/lib/wamp-parser.js).

Elad

**Comment by oberstet** [comment]
I would call that "done" for now. The rest is filling in details here and there. And that can be done "on the go".
