### ISSUE TITLE
Doc hosting

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-java#168]
"Free javadoc hosting for any open source Central Maven Repository project. "

https://www.javadoc.io/

This seems to be the place to publish docs for a Java project.

Eg here is akka-wamp: 

http://angiolep.github.io/projects/akka-wamp/

**Comment by oberstet** [comment]
So this seem to require publishing to Maven Central:

> any open source Central Maven Repository project.

**Comment by oberstet** [comment]
An alternative would be to create a separate, dedicated docs artifacts repo into which we publish the final generated docs, and then host that using GitHub pages, like we do for AB C++:

* https://github.com/crossbario/autobahn-cpp-docs
* https://crossbario.github.io/autobahn-cpp-docs/

**Comment by om26er** [comment]
I will dig into javadoc.io and think that's where ours should live.

**Comment by om26er** [comment]
@oberstet So I overlooked the comment that said we need the jar uploaded to maven first. I took a look and found that GitHub pages is very simple. So I guess we can go with GH pages. Can you please create a new project autobahn-java-docs and I'll put docs html there.

**Comment by om26er** [comment]
sample deployment: https://om26er.github.io/sample-temp/

**Comment by oberstet** [comment]
@om26er sorry, missed that, here: https://github.com/crossbario/autobahn-java-docs - the docs look great!

**Comment by oberstet** [comment]
@om26er is it possible to generate the docs without frames?

**Comment by oberstet** [comment]
ahh, there is a "no frames" link being generated .. ok

**Comment by oberstet** [comment]
the docs now live on https://crossbario.github.io/autobahn-java-docs/
