### ISSUE TITLE
Pass along executor service object

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-java#195]
What we probably should do is pass that executor service object down the consumption line (eg to Session).

**Comment by oberstet** [comment]
Essentially, whereever we use the "async" variants of CompletableFuture methods, we need to refer a possibly user provided executor All async methods without an explicit Executor argument

**Comment by oberstet** [comment]
When no explicit executor is passed into "async" methods, then these will use https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ForkJoinPool.html#commonPool--

**Comment by oberstet** [comment]
The executor should probably be a) the last argument and b) be optional. Eg as in

```java
CompletableFuture<Void> 	acceptEitherAsync(CompletionStage<? extends T> other, Consumer<? super T> action, Executor executor)
Returns a new CompletionStage that, when either this or the other given stage complete normally, is executed using the supplied executor, with the corresponding result as argument to the supplied function.
static CompletableFuture<Void> 	
```

**Comment by om26er** [comment]
ForkJoinPool.commonPool is indeed the answer but there is one problem, it was only introduced in Android with API level 24 aka Android 8.0 (not released yet). So in our cases we may want to add conditional code everywhere, something like:
```
if (exector != null) {
    // pass executor to completeable future methods.
} else {
    // Don't pass the executor. Internally it calls ForkJoinPool.commonPool()
}
```

**Comment by oberstet** [comment]
Yeah, I see!

Here is a suggestion: in our own examples and demo code, we use an explicit pattern everywhere where we create a single-thread executor and feed that into everything. This is to "encourage best practice".

And the same time we overload the constructors of the respective classes so they allow for creation without providing an executor. In that case we set the `this.mExecutor` to "null" internally.

Then, when we do someting `async`, we check `this.mExecutor` and only use it if it is non-null.

**Comment by om26er** [comment]
Well, actually there was some confusion, in android it was introduced in API 24, which is Android 7.0 and that's what we are aiming for ABJv2, so we are good to go.

**Comment by oberstet** [comment]
Oh, even better!

Another thing, as I am looking over Session, I think it would make sense if the contract for ITransportHandler would allow the onXXX callbacks to throw exceptions.

Like as we do already in basically all of them, eg in onMessage we do throw ProtocolError.

And that is fine! I just say: let's make it clear, allow that in ITransportHandler, but then define what's happening.

Eg with ProtocolError being thrown in onMessage, the Transport might disconnect the Session, maybe even disconnect the underlying network. Not sure. But it seems we need to define what these exceptions do ...

**Comment by om26er** [comment]
I guess we can close this one ?

**Comment by oberstet** [comment]
yes, we can close it. btw, I plan to introduce ABJ on the workshop starting from this code piece https://github.com/crossbario/autobahn-java/#plumbing
