### ISSUE TITLE
Accelerate CI

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-java#200]
We have a working CI now. But it could be faster when we didn't build the whole toolchain image locally each time:

https://github.com/crossbario/autobahn-java/blob/master/.travis.yml#L9

Instead, we might consider prebuilding such a toolchain image containing a JDK, Netty, and all our dependencies. We could then publish that image to Dockerhub in the hope that fetching from Dockerhub and presumably caching the image localally with Travis is faster.

**Comment by om26er** [comment]
We could speed it up by only building the docker image *if* the Dockerfile changed.

**Comment by om26er** [comment]
fixed by https://github.com/crossbario/autobahn-java/pull/289

**Comment by om26er** [comment]
specific change https://github.com/crossbario/autobahn-java/pull/289/commits/584bfe0b1e2f651b8b20125a90db15591f18f8d0
