### ISSUE TITLE
Example of using POJOs with ABJ

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-java#208]
Was "Add guides to Jackson/ObjectMapper"

* http://www.baeldung.com/jackson-object-mapper-tutorial
* https://fasterxml.github.io/jackson-databind/javadoc/2.7/com/fasterxml/jackson/databind/ObjectMapper.html

**Comment by oberstet** [comment]
Apparantly, the Jackson ObjectMapper can be used together with CBOR:

* https://github.com/FasterXML/jackson-dataformats-binary/tree/master/cbor#usage

```java
CBORFactory f = new CBORFactory();
ObjectMapper mapper = new ObjectMapper(f);
// and then read/write data as usual
SomeType value = ...;
byte[] cborData = mapper.writeValueAsBytes(value);
SomeType otherValue = mapper.readValue(cborData, SomeType.class);
```

**Comment by om26er** [comment]
> Apparantly, the Jackson ObjectMapper can be used together with CBOR (com.fasterxml.jackson.dataformat.cbor.CBORFactory):

Yes, we are already making use of it in our code for some cases, especially for parsing incoming messages. https://github.com/crossbario/autobahn-java/blob/master/autobahn/src/main/java/io/crossbar/autobahn/wamp/types/CBORSerializer.java#L42 -- We can definitely look into extending it for other purposes as well.

**Comment by oberstet** [comment]
The main problems I see are these:

* how do we allow the user to specify that he expects the return value of a RPC be single-positional with a class type T, so the ObjectMapper could automatically return an instance of T (or more precise, session.call would return a CompletableFuture<T> instead of a generic CompletableFuture<CallResult>)?
* how do we use the ObjectMapper at the WAMP message level letting everything dynamically typed, but only args/kwargs (optionally) under user type control?

Not sure, maybe I am blind. But how would the above work out?

I mean, the end goal would be to make it easier for users operating with native POJO instances.

**Comment by oberstet** [comment]
We should have a more complex example that demonstrates the use of POJOs with ABJ. Actually, this is more that a docs issue, since it touches the daily use of the library.

**Comment by oberstet** [comment]
Here is how the old AB allowed users to specific the POJO type for a _return value_ (eg from doing a WAMP call).

* https://github.com/crossbario/autobahn-java/blob/version-1/Autobahn/src/de/tavendo/autobahn/Wamp.java#L151
* https://github.com/crossbario/autobahn-java/blob/version-1/Autobahn/src/de/tavendo/autobahn/WampConnection.java#L336
* https://github.com/crossbario/autobahn-java/blob/version-1/Autobahn/src/de/tavendo/autobahn/WampConnection.java#L301
* https://github.com/crossbario/autobahn-java/blob/version-1/Autobahn/src/de/tavendo/autobahn/WampReader.java#L131

**Comment by om26er** [comment]
I have been looking into this, one problem that I am facing right now is how to implement this with Session.call(), that methods returns a CompletableFuture<CallResult>, so its clear that to read any result from that CallResult, we'll have to do some sort of casting.

A cleaner approach would be to follow the same pattern as Session.subscribe() and Session.register() use i.e. provide a callback method as parameter, The signature of that method could be anything like

```
myCallbackMethod(List<Person> args, Map<String, ?> kwargs);
```

Thoughts ?

**Comment by oberstet** [comment]
Would this work for `ISession`?

```java
    CompletableFuture<CallResult> call(String procedure,
                                       List<Object> args,
                                       Map<String, Object> kwargs,
                                       CallOptions options);

    CompletableFuture<T> call(String procedure,
                              List<Object> args,
                              Map<String, Object> kwargs,
                              TypeReference<T> resultType,
                              CallOptions options);
```

**Comment by om26er** [comment]
Actually, I think this might be a cleaner approach
```
    <T> CompletableFuture<T> call(String procedure,
                                  List<Object> args,
                                  Map<String, Object> kwargs,
                                  Class<T> resultType,
                                  CallOptions options);
```

The biggest advantage of that is We have no dependency on Jackson in our public API.

**Comment by oberstet** [comment]
Yeah, makes sense! Also, +1 for your code variant. Lets try that.

**Comment by oberstet** [comment]
This is implemented (probably not yet 100% complete), but in principle. We also have example code
