### ISSUE TITLE
Decide about switch to Netty on Android

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-java#212]
Do we need the WebSocket implementation we have? For Android? Can we replace it with Netty, and what would be the ups/downs of that?

**Comment by om26er** [comment]
According to this issue: https://github.com/netty/netty/issues/2127 Netty(atleast websockets) should work fine on Android. I did ask a relevant question a few days ago for which I am still waiting their answer: https://github.com/netty/netty/issues/7139

**Comment by om26er** [comment]
I wrote an experimental app that works on Android 7.0+ using Netty based backed: https://github.com/om26er/pigpio-wamp-android

**Comment by oberstet** [comment]
Here are sizes from current toolchain image:

```
oberstet@thinkpad-t430s:~/scm/crossbario/autobahn-java$ make check_toolchain 
docker run -it --rm crossbario/autobahn-java:netty /bin/bash -c "ls -la /autobahn && du -hs /autobahn"
total 4296
drwxr-xr-x  2 root root    4096 Aug 28 15:56 .
drwxr-xr-x 48 root root    4096 Aug 28 17:10 ..
-rw-r--r--  1 root root   87633 Aug 28 15:56 autobahn-17.8.2.jar
-rw-r--r--  1 root root   55784 Aug 28 15:56 jackson-annotations-2.8.0.jar
-rw-r--r--  1 root root  282438 Aug 28 15:56 jackson-core-2.8.8.jar
-rw-r--r--  1 root root 1238590 Aug 28 15:56 jackson-databind-2.8.8.jar
-rw-r--r--  1 root root   50727 Aug 28 15:56 jackson-dataformat-cbor-2.8.8.jar
-rw-r--r--  1 root root   30613 Aug 28 15:56 jackson-dataformat-msgpack-0.8.13.jar
-rw-r--r--  1 root root  116124 Aug 28 15:56 msgpack-core-0.8.13.jar
-rw-r--r--  1 root root  249873 Aug 28 15:56 netty-buffer-4.1.2.Final.jar
-rw-r--r--  1 root root  299080 Aug 28 15:56 netty-codec-4.1.2.Final.jar
-rw-r--r--  1 root root  536836 Aug 28 15:56 netty-codec-http-4.1.2.Final.jar
-rw-r--r--  1 root root  661454 Aug 28 15:56 netty-common-4.1.2.Final.jar
-rw-r--r--  1 root root  303527 Aug 28 15:56 netty-handler-4.1.2.Final.jar
-rw-r--r--  1 root root   25655 Aug 28 15:56 netty-resolver-4.1.2.Final.jar
-rw-r--r--  1 root root  415789 Aug 28 15:56 netty-transport-4.1.2.Final.jar
4.2M	/autobahn
```

---

Conclusions:

1. an Android dev that only needs plain WebSocket, _might_ want to have ABJ without the Jackson, Netty etc stuff because of size
2. an Android dev that wants WAMP will currently get a huge bundle of deps of which Netty dominates
3. a server dev can use ABJ/Netty and sizes in this scale simply don't matter anymore

**Comment by oberstet** [comment]
So ideally, ABJ would support a) older Android devices and b) only add small size to an apk. 

* a): should we use a polyfill?
* b): should we use our own WS impl (instead of Netty) to cut down the size?

**Comment by om26er** [comment]
Using lambdas in older android versions is not a problem; android studio 3.0 (to be released soon) adds that support.

The main issue to address is to keep the source compatible with older Androids.

Since Java does not support conditional imports, a low-cost solution that we can do while maintaining a single source tree is to come up a script that replaces specific import lines to look something like:

```
- import java.util.concurrent.CompletableFuture;
+ import java8.util.concurrent.CompletableFuture;
```

Regarding size, I did some testing and my Android app that uses autobahn and all the libraries (netty/jackson) sized ~500kb, not sure what magic Google does to keep size low. Though responses from Netty project suggest that Android and Netty might not be best friends https://github.com/netty/netty/issues/7139

So we probably need to come up with a WebSocket transport that talks WAMP based on our WebSocket impl.

**Comment by oberstet** [comment]
> The main issue to address is to keep the source compatible with older Androids.

I see. Let's skip that for now! We don't support older Androids ..

> So we probably need to come up with a WebSocket transport that talks WAMP based on our WebSocket impl.

Ok, then adding a WAMP transport on top of our own WebSocket implementation for Android is s.th. you could work on.

**Comment by om26er** [comment]
Closing this as we decided above ;-)

**Comment by om26er** [comment]
The WAMP transport over our WebSocket impl is tracked via https://github.com/crossbario/autobahn-java/issues/146
