### ISSUE TITLE
Ping-Pong support enable

### ISSUE THREAD

**Issue by Ktirumalsetty** [crossbario/autobahn-java#217]
Does the latest code has Ping-Pong support in code 

I can see ping pong support but there is no methods or callbacks to support ping pong

**Comment by om26er** [comment]
Right, we currently don't expose the ping/pong API, mostly because this is in progress, see https://github.com/crossbario/autobahn-java/issues/31. Also note that we will introduce automatic ping/pong as well https://github.com/crossbario/autobahn-java/issues/32
