### ISSUE TITLE
Add session argument to session observers

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-java#219]
Currently, the lifecycle observers for session look like

```java
public void onJoinHandler1(SessionDetails details) {
...
```

In particular, the observer does _not_ get a reference to the session from which the lifecycle event is triggered.

This can be problematic, eg say I want to add an observer function which resides somewhere where it doesn't have a reference to the triggering session.

We can avoid that by modifying the observer interface like this:

```java
public void onJoinHandler1(Session session, SessionDetails details) {
...
```

So essentially, we need to add `session` to _all_ observer as the first argument.

**Comment by oberstet** [comment]
Above also has the benefit of allowing to observe multiple sessions with _one_ listener function - as the listener gets the session reference, it can still differentiate from where the lifecycle event was actually coming from.

**Comment by om26er** [comment]
should the sessionID on the Session be public so that it can be accessed or is that supposed to be for internal use only ?

This PR adds Session reference to onJoin: https://github.com/crossbario/autobahn-java/pull/222

**Comment by oberstet** [comment]
@om26er yep, sessionID should be public, but probably "read-only", maybe expose it via a getter?

Here is one use case:

* "on-join" listener is a free standing function that wants to publish an event, but exclude the triggering session from receivers
* the new "on-join" listener has the triggering "session", and hence the body of the function can use that to a) publish an event, and b) read the sessionID from "session", and use that for exclude ..

**Comment by oberstet** [comment]
Ah, we should have `session` as a first argument for _all_ 6 OnXXX listeners.

The PR merged added it for onJoin, but the other 5 are missing ..

**Comment by om26er** [comment]
alright, on it.

**Comment by om26er** [comment]
> alright, on it.

Done, fix here: https://github.com/crossbario/autobahn-java/pull/224

**Comment by om26er** [comment]
> @om26er yep, sessionID should be public, but probably "read-only", maybe expose it via a getter?

added a getID() method to session: https://github.com/crossbario/autobahn-java/pull/224

**Comment by oberstet** [comment]
Awesome, so this is on master .. closing
