### ISSUE TITLE
Add session reference to InvocationDetails

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-java#220]
Currently, invocations need to be served by user functions which have to implement:

```java
@FunctionalInterface
public interface IInvocationHandler {
    CompletableFuture<InvocationResult> run(List<Object> args, Map<String, Object> kwargs,
                                            InvocationDetails details);
}
```

https://github.com/crossbario/autobahn-java/blob/master/autobahn/src/main/java/io/crossbar/autobahn/wamp/types/IInvocationHandler.java

**In particular, there is no reference to the session object from which the invocations comes**

We have 2 options to provide the invoked method with a reference to session:

1. add another argument, eg `IInvocationHandler.run(arg, kwargs, session, details)`
2. add `session` to `InvocationDetails`

The latter seems to be nicer ..

**Comment by om26er** [comment]
Session object is now part of InvocationDetails, pull request here: https://github.com/crossbario/autobahn-java/pull/223
