### ISSUE TITLE
Revise IEventHandler and add EventDetails

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-java#221]
Currently, the event handler interface looks like this:

```java
@FunctionalInterface
public interface IEventHandler<R> {
    R run(List<Object> args, Map<String, Object> kwargs);
}
```

https://github.com/crossbario/autobahn-java/blob/master/autobahn/src/main/java/io/crossbar/autobahn/wamp/types/IEventHandler.java

This should be changed to:

```java
@FunctionalInterface
public interface IEventHandler {
    CompletableFuture<ReceptionResult> run(List<Object> args, Map<String, Object> kwargs,
                                            EventDetails details);
}
```

Notable, we need the following new type classes:

* EventDetails
* ReceptionResult

The EventDetails must contain a reference to session (among other stuff we can add later).

There is 1 aspect that deserves explanation: above will allow an IEventHandler to actually return sth (async) - the ReceptionResult. We can leave that competely empty for now (the class).

This differs from all other ABs, but is in preparation of a WAMP feature we will add:

* acknowledged event _delivery_

See: `EVENT_RECEIVED` https://github.com/wamp-proto/wamp-proto/issues/280

**Comment by om26er** [comment]
Following PR makes the changes as requested in this issue. https://github.com/crossbario/autobahn-java/pull/241

**Comment by oberstet** [comment]
on master now
