### ISSUE TITLE
WebSocket client initiated heartbeating

### ISSUE THREAD

**Issue by ospavel** [crossbario/autobahn-java#238]
Test on desktop Java 8 with Netty the code from demo (modify it a little, and use wamp.2.json instead of wamp.2.cbor):
`       
        mSession = new Session(mExecutor);
        
        // make some subscriptions
        mSession.addOnJoinListener(this::onJoinHandler);

        //
        mSession.addOnDisconnectListener((session, b) -> System.out.println("On disconnect") );

        // now create a transport list for the transport to try and which will carry our session
        List<ITransport> transports = new ArrayList<>();

        // in this case, the only transport we add is a WAMP-over-WebSocket
        // implementation on top of Netty client WebSocket
        transports.add(new NettyTransport(url));

        // now create a authenticator list for the session to announce
        // and which will authenticate our session
        List<IAuthenticator> authenticators = new ArrayList<>();

        // in this case, we don't care about authentication and so
        // the only authenticator we announce is the (pseudo) "anyonymous"
        authenticators.add(new AnonymousAuth());

        // finally, provide everything to a Client instance
        client = new Client(transports, mExecutor);

        // leave room for adding more than one sessions.
        client.add(mSession, realm, authenticators);

        CompletableFuture<ExitInfo> exitInfoCompletableFuture = client.connect();
`
When I switch off network cable there is no any reaction during infinite time. After network cable switched back - no reaction and no further work. 
Thus it is not simple to know about connection problem for reconnection call.

**Comment by om26er** [comment]
Currently autobahn-java only support CBOR as serializer, implementing JSON serializer would be pretty simple but that's something we haven't looked into just yet.

Does the same issue happen with wamp.2.cbor ?

**Comment by oberstet** [comment]
> When I switch off network cable there is no any reaction during infinite time.

Without sending anything, TCP cannot distinguish between an infinitesimal slow connection and a broken connection (at least not when on different L2 network segments - try the same on a LAN). This is TCP (when used over WAN).

There are 2 things here to fix this:

1. use a WAMP router that has WebSocket auto-pingpong/heartbeating (Crossbar.io has that)
2. AutobahnJava needs a client initiated WebSocket auto-pingpong/hearbeating as well

1. will allow the router to quickly detect a broken client connection and clean up resources
2. will allow the client (your AutobahnJava based program) to quickly detect a broken router connection and clean up resources

We don't have 2. yet - but we should.

**Comment by oberstet** [comment]
Again, this is very important for production use, but also in container based scenario where the order of container startup might not be fixed, and an ABJ component might be up earlier than the router, or when the router is restarted.

**Comment by om26er** [comment]
@oberstet Can you link an example on how other WAMP implementations are doing this ? Should it be a WebSocket ping frame ? what should be the timeout for it and how often shall we send the ping (how shall we expose that functionality if we want the frequency to be configurable).

Also I presume Crossbar itself does have ping-pong i.e. server initiated, is that on by default ?

**Comment by om26er** [comment]
Also, is the heartbeat interval relevant to the success of prior request ?

example: If I my heartbeat is configured to run every 10 seconds shall those 10 seconds begin after the PONG for previous PING returns or right from the time when PING was sent ?

**Comment by om26er** [comment]
First implementation attempt is available: https://github.com/crossbario/autobahn-java/issues/238

**Comment by om26er** [comment]
@oberstet this is done, closing.

**Comment by pkyad** [comment]
By any chance is it possible to use WebSocketOptions with this to adjust the setReconnectInterval
