### ISSUE TITLE
Expose WAMP handshake parameters

### ISSUE THREAD

**Issue by om26er** [crossbario/autobahn-java#243]
We need to be able to define which wamp protocol to use (e.g. wamp.2.cbor or wamp.2.json etc). Right now its hardcoded. We also need to be able to define the max websocket framesize which is currently hard coded to 655360.

The relevant code is [here](https://github.com/crossbario/autobahn-java/blob/2b6741ff3dbfcf6ccbb70470adb16e71305f35ad/autobahn/src/main/java/io/crossbar/autobahn/wamp/transports/NettyTransport.java#L123)

**Comment by oberstet** [comment]
Nearly;)

What we usually do in AB libraries for WebSocket:

* allow the user to configure the set of serializers he is willing to use
* then, when the client connects, the actual serializer is auto-negotiated (using the WebSocket opening handshake)

So a WebSocket client announces a _list_ of WebSocket subprotocols to use: `wamp.2.cbor, wamp.2.json` and the server (Crossbar.io) will chose the first one it is willing/able to speak.

RawSocket is simpler: http://wamp-proto.org/static/rfc/draft-oberstet-hybi-crossbar-wamp.html#handshake

There is no negotiation during the opening handshake.

**Comment by oberstet** [comment]
So for (Netty based) WebSocket in ABJ, I see these options:

a)

As Jackson has CBOR, JSON and MessagePack support built in anyway by default (is this true?), let the `NettyTransport` just announce all 3 (list of WebSocket subprotocols), with order cbor>msgpack>json, and then actually use the serializer chosen by the router.

No API change at all. But no client (user) influence also.

b)
```java
public NettyTransport(String uri, List<ISerializer> serializers, ExecutorService executor)
```

Same as above, but only announce exactly the serializers that the user wants.

---

With both, the WebSocket client class in ABJ then really needs to pay attention to the actual WebSocket subprotocol chosen by the router, as that will determine which serializer to use.

**Comment by om26er** [comment]
So what about the max WebSocket frame size parameter ? also what should be the default value of that (currently 655360),

**Comment by om26er** [comment]
Shall we add more serializers(json, msgpack) today or is that something for future ?

**Comment by oberstet** [comment]
rgd websocket options, best would be to add https://github.com/crossbario/autobahn-java/blob/master/autobahn/src/main/java/io/crossbar/autobahn/websocket/WebSocketOptions.java#L20 as another parameter to (an overload of) the constructor of `NettyTransport`.

rgd serializer support: for completeness we probably want to add it (json and msgpack, not ubjson, as the latter is not supported by Jackson?) now, as it is straight forward, not a lot work. this despite that a user may have little reasons to use anything else but CBOR.

**Comment by om26er** [comment]
> rgd serializer support: for completeness we probably want to add it (json and msgpack, not ubjson, as the latter is not supported by Jackson?) now, as it is straight forward, not a lot work. this despite that a user may have little reasons to use anything else but CBOR.

One reason might be if someone is using a WAMP router that does not talk CBOR, but I am not sure how much we care about that.

**Comment by oberstet** [comment]
@om26er yes, WAMP routers without CBOR support: of course Crossbar.io supports all serializers, but we want to play nice with other WAMP routers too. So yes.

**Comment by om26er** [comment]
This PR https://github.com/crossbario/autobahn-java/pull/246 adds MessagePack and JSONSerializers.

> public NettyTransport(String uri, List<ISerializer> serializers, ExecutorService executor)

regarding this, the currently proposed implementation takes List<String> instead of List<ISerializer> so that we only construct a serializer when needed.

**Comment by om26er** [comment]
Merged the branch as that was blocking me. If we want to take a different approach for the above question, we can come back to it later.
