### ISSUE TITLE
Session.join() should be void ?

### ISSUE THREAD

**Issue by om26er** [crossbario/autobahn-java#255]
currently Session.join returns a null object reference in place of CompletableFuture<SessionDetails>, look [here](https://github.com/crossbario/autobahn-java/blob/584b4841b5c5cdfc978bf40eb686cbdbb4f88b0c/autobahn/src/main/java/io/crossbar/autobahn/wamp/Session.java#L654)

I did some investigation and looked into the WAMP proto [spec](http://wamp-proto.org/static/rfc/draft-oberstet-hybi-crossbar-wamp.html#rfc.section.7.1.1) and found that we don't really have a differentiator while sending a HELLO, so we can't really resolve our Session.join() future.

In this case, how about changing Session.join() to not return anything ?

**Comment by oberstet** [comment]
Session.join could create a Future, store it to a local private attribute, and later resolve that Future when the Session actually has joined, and the SessionDetails can be constructed.

**Comment by om26er** [comment]
> As this currently is not the case, this is probably a bug, as in "missing return value for Session.join".

@oberstet the problem is that we don't have any unique ID when we send a request to join a session. Should we rely on the realm name to resolve the future on Welcome message ?

**Comment by om26er** [comment]
btw, join is a void in ABPy: https://github.com/crossbario/autobahn-python/blob/master/autobahn/wamp/protocol.py#L352

**Comment by oberstet** [comment]
> the problem is that we don't have any unique ID when we send a request to join a session. 

This would only be a problem if a WAMP transport could run more than one session - which is not the case.

In other words, whenever a WELCOME message is received, this must have been because we sent HELLO earlier - for that very session.

ABPy will then fire "join" observers: https://github.com/crossbario/autobahn-python/blob/master/autobahn/wamp/protocol.py#L483

In ABJ, we could do similar _and_ return a Future from "Session.join"

**Comment by om26er** [comment]
> In ABJ, we could do similar and return a Future from "Session.join". In other words: the fact that ABPy does not return anything is probably sth we can do better in ABJ;)

sounds good =) here is a fix: https://github.com/crossbario/autobahn-java/pull/264

**Comment by om26er** [comment]
This is done.
