### ISSUE TITLE
Docs and v2 announcement

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-java#259]
The basic docs should include a a) code teaser on WAMP usage in the README.md, then b) docs auto-generated from the code:

* https://github.com/crossbario/autobahn-java/issues/126
* https://github.com/crossbario/autobahn-java/issues/168

and probably c) a updated version of docs/WAMP Programming ...md

When we have that, I'd say it's time to announce the awesome news: AB v2 is here =) With TLS and WAMP v2 and on Java 8 / Netty. Android at the WebSocket level should work too? We should invite for testing and for usage feedback.

**Comment by om26er** [comment]
Ok, we did the release announcement already.

Next release will contains WAMP for Android and improvements to the WebSocket code.
