### ISSUE TITLE
Version badges

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-java#276]
As a user, I would like to immediately see with which version of the library I am working with. We should have

* a badge at the top of the README that shows the ABJ version
* a version number in the docs header

**Comment by om26er** [comment]
> a badge at the top of the README that shows the ABJ version
That was fixed with the move to javadoc.io, the reasons for the move are given here: https://github.com/crossbario/autobahn-java/pull/298



> a version number in the docs header
Fixed by the move to javadoc.io
