### ISSUE TITLE
WebSocket implementation uses deprecated org.apache.http

### ISSUE THREAD

**Issue by om26er** [crossbario/autobahn-java#278]
Exactly what the title says. Fortunately we only use BasicNameValuePair from that library, who's sole purpose to act as a dictionary. Lets use a HashMap<String, String> for that. 

https://github.com/crossbario/autobahn-java/pull/277/commits/7b99e9899e0e59730d18a7f959f15e8269da3195 fixes this.

**Comment by oberstet** [comment]
this is merged
