### ISSUE TITLE
Doc page about coroutines and Kotlin

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-java#286]
Will Java get coroutines, and if so, when? (it lacks coroutines with Java 8 at least).
What about Kotlin coroutines? Does Kotlin work with ABJ?

* https://dzone.com/articles/concurrency-java-futures-and-kotlin-coroutines-1
* https://kotlinlang.org/docs/reference/coroutines.html

**Comment by long76** [comment]
@oberstet i agree, move to kotlin!)))

**Comment by oberstet** [comment]
won't fix: for now we won't move to kotlin -- ABJs APIs would need to be massivel changed
