### ISSUE TITLE
Optionally support WAMP on Android < 7.0

### ISSUE THREAD

**Issue by om26er** [crossbario/autobahn-java#290]
We hear lots of requests from people wanting to use WAMP on pre Android 7.0 devices. Our API uses Java8 specific features which are not officially available on older Androids. Though this project https://github.com/streamsupport/streamsupport allows just that.

**Comment by om26er** [comment]
I have a script that changes the code on the fly to use that library, proposed here: https://github.com/crossbario/autobahn-java/pull/291

**Comment by om26er** [comment]
This landed, we may want to consider a autobahn-android-legacy(-backport or -something) as a separate release to the central repositories.

**Comment by andzejsw** [comment]
Any progress on this?

**Comment by oberstet** [comment]
sorry to say: it's not a priority and we don't have the resources to support that "officially". for one, it would require another release channel, and more so, I'd expect that the shim that @om26er used to make it work on android <7 only works somewhat (will trigger issues, and hence work, down the line) .. 

we support Android 7+  (well, and Java8/Netty of course) and we should clearly state that in the docs and https://github.com/crossbario/autobahn-java/blob/master/README.md - which seems to be missing right now:(

> if you are using this in a commercial context, we might be able to add support under a commercial contract. pls PM me if you're interested in that
