### ISSUE TITLE
Android: Code run inside callbacks does not update UI

### ISSUE THREAD

**Issue by om26er** [crossbario/autobahn-java#301]
Any code that is run inside a method that is resolved from a CompleteableFuture is executed in a background thread, hence if our code tries to update the app UI that does not work. It also does not throw any error which is a bummer as that makes me nervous.

The workaround is to run the code inside a runOnUIThread() closure. But if we aim to support android as a first class citizen we need to come up with something sophisticated.

**Comment by oberstet** [comment]
@om26er have you set the executor where the callback is to be invoked? when the callback of CompletableFuture is meant to directly do UI stuff, then the executor needs to be the main/UI thread.

**Comment by om26er** [comment]
All async methods associated with CompleteableFuture execute in the background, so the issue exists if we pass the executor or not. Though it seems the non-async variants are what we should be using for cases where the WAMP session have to talk to user code.

`aFuture.thenAcceptAsync() vs aFuture.thenAccept()` -- The latter is what we should be making use of for Session to user-code calling.

**Comment by oberstet** [comment]
If the async methods cannot be made to run on the UI thread by passing an appropriate executor (which I am not fully convinced, but lets assume), then the solution could be doing the same as the receiving background thread in ABJ websocket implementation does (I think, when I remember): using some post mechanism to drop events into the UI event loop driving the UI thread.

**Comment by om26er** [comment]
> If the async methods cannot be made to run on the UI thread by passing an appropriate executor (which I am not fully convinced, but lets assume)

So there is no such executor inside the Executors class. So we have to create a custom executor with very little code:
```
public class CurrentThreadExecutor implements Executor {
    public void execute(Runnable r) {
        r.run();
    }
}
```
We should ship that class as part of our library. Also this enablement depends on https://github.com/crossbario/autobahn-java/pull/307

**Comment by om26er** [comment]
@oberstet So I think it will make sense to automatically use the CurrentThreadExecutor when the platform is android, unless an override executor is provided.

**Comment by om26er** [comment]
fixed by https://github.com/crossbario/autobahn-java/pull/307
