### ISSUE TITLE
WAMP: Implement cryptosign authentication

### ISSUE THREAD

**Issue by om26er** [crossbario/autobahn-java#308]
TBD.

**Comment by oberstet** [comment]
A first thing to decide is: what NaCl Java library to use?

I would rule out anything using JNI to interface to a native NaCl library - means, the library must be pure Java.

* https://github.com/neilalexander/jnacl
* https://github.com/InstantWebP2P/tweetnacl-java
* https://github.com/freeeve/nacl-java

**Comment by om26er** [comment]
> A first thing to decide is: what NaCl Java library to use?

Out of the three that you linked, I believe tweetnacl-java is worth looking into.

https://github.com/freeeve/nacl-java <-- Does not support Android
https://github.com/neilalexander/jnacl <-- This is incomplete and does not support signing.

My current proposal is using https://github.com/joshjdevl/libsodium-jni because, it was really easy to setup, is published to maven and has a similar API to what we are using in Python. This also seems to be in very active development.

**Comment by oberstet** [comment]
For now, if a JNI based library works, ok, then we can use it if it works (long term I think a pure Java impl would be desirable).

In the class of libsodium based Java libs, there also is: https://github.com/muquit/libsodium-jna

No clue which one is better.

**Comment by oberstet** [comment]
rgd examples, here is https://github.com/crossbario/crossbar-examples/tree/master/authentication/cryptosign

**Comment by om26er** [comment]
@oberstet CryptoSign is working using this PR https://github.com/crossbario/autobahn-java/pull/347 -- I am using static authentication example from crossbar-examples.

So I guess we can land that now and later change the underlying library.

**Comment by oberstet** [comment]
cool!

**Comment by om26er** [comment]
@oberstet I'll do an example. The PR is still not merged, so would be cool if you could review/merge that. https://github.com/crossbario/autobahn-java/pull/347

**Comment by oberstet** [comment]
@om26er ok, merged! one note: you could have a quick look if the JNI bindings of the library selected has bindings for the entry points we will need for WAMP-cryptobox (end-2-end encryption) - when we come to that
