### ISSUE TITLE
Expose API for WS pings/pongs

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-java#31]
There should be a `sendPing` method, and an `onPing` method with a default implementation just replying with pong.

**Comment by oberstet** [comment]
Yep, this should be exposed at the WebSocket API level. Should be addressed as part of https://github.com/crossbario/autobahn-android/issues/92

**Comment by om26er** [comment]
fixed by https://github.com/crossbario/autobahn-java/pull/287
