### ISSUE TITLE
Call Result error - Exceptions

### ISSUE THREAD

**Issue by antoniotaranto** [crossbario/autobahn-java#316]
I could not return an error (throw) in a call.

According #184 . Errors in calls (exception, throw, etc) need to be implemented.

"
Call Result processing is already in master, **error processing still needs to be implemented.**
"

Is it really pending?

**Comment by om26er** [comment]
Hi! I have just verified and found that exceptions are indeed being thrown, though you have to catch them through CompleteableFuture. Check below code:
```
private static void onJoinCallback(Session session, SessionDetails details) {
    CompletableFuture<CallResult> resultFuture = session.call("com.myapp.method1");
    resultFuture.whenComplete((callResult, throwable) -> {
        if (throwable == null) {
            System.out.println("Call results: " + callResult.results);
        } else {
            // Run your exception handling code here.
            throwable.printStackTrace();
        }
    });
}
```

Though I have just found that we are currently only processing the URI of the wamp error. Its args and kwargs are being ignored, though we will fix that.

**Comment by om26er** [comment]
@antoniotaranto Did you figure this one out or is that still an issue ?

**Comment by antoniotaranto** [comment]
Hi, , sorry for the delay.
But now everything is working.
Thanks.
