### ISSUE TITLE
Automatic hearbeat using WS pings/pongs

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-java#32]
There should be an automatic heartbeat feature to quickly recognize broken connections.

**Comment by oberstet** [comment]
This is an important one. Server-initiated WS ping/pong will only allow the server to detect broken connections quickly .. not the client. One needs client-initiated WS ping/pong **in addition**. You need both.

https://github.com/crossbario/autobahn-android/issues/92

**Comment by william-ferguson-au** [comment]
You don't necessarily need both. You just need the client to record the last time it received a ping from the server and have a thread that uses that as a timeout to kill the connection.

**Comment by oberstet** [comment]
@william-ferguson-au interesting idea. could work. I guess I'd still call it a "workaround", but still. unfort., it won't work in browsers (unrelated to AutobahnAndroid, but relevant for AutobahnJS), because the W3C WS API doesnt expose any ping/pong (not receiving, not sending). anyway: we do want to have client initiated (and timed out) WS ping/pong in AutobahnAndroid v2 ..

**Comment by om26er** [comment]
I am working on this with some ideas, should have a solution soon. This should also deal with https://github.com/crossbario/autobahn-java/issues/36

**Comment by om26er** [comment]
fixed by https://github.com/crossbario/autobahn-java/pull/287
