### ISSUE TITLE
Reflection based callee proxy support

### ISSUE THREAD

**Issue by darkl** [crossbario/autobahn-java#334]
Hi!

I thought to suggest some feature which WampSharp has - one can take advantage of the fact that Java is strongly typed and define application contracts using meta-data.

For example, [reflection based caller](http://wampsharp.net/wamp2/roles/caller/reflection-based-caller/) allows a user to declare a contact such as:

```java
package net.codesharp;

import java.util.concurrent.CompletableFuture;

public interface IAddCalculator {
    @WampProcedure("com.example.add2")
    CompletableFuture<Integer> addAsync(int x, int y);
}
```

And then ask for an implementation of this interface from AutobahnJava. Whenever the user calls addAsync on the received instance, it will automagically call `session.call("com.example.add2", x, y)` and return the desired result.

I actually implemented some draft of this mechanism. You can find it [here](https://gist.github.com/darkl/73db93167d9a1201bf61250539a26fde). See the usage example in Main.java. You can run it, it works! but I think this should be integrated in AutobahnJava with nicer api.
Feel free to do whatever you want to do with this code. I think this feature can be very useful and convenient for AutobahnJava users.

Elad

**Comment by darkl** [comment]
Here's another nice example: using the well known session meta-api. [See here](https://gist.github.com/darkl/36a8f01488651caed2ec8d89797d6622)

```java
import java.util.concurrent.CompletableFuture;

public interface IWampSessionDescriptorProxy {
    /**
     * Obtains the number of sessions currently attached to the realm.
     *
     * @return The number of sessions currently attached to the realm.
     */
    @WampProcedure("wamp.session.count")
    CompletableFuture<Long> countSessionsAsync();

    /**
     * Retrieves a list of the session IDs for all sessions currently attached to the realm.
     *
     * @return List of WAMP session IDs (order undefined).
     */
    @WampProcedure("wamp.session.list")
    CompletableFuture<Long[]> getAllSessionIdsAsync();

    /**
     * Retrieves information on a specific session.
     *
     * @param sessionId The session ID of the session to retrieve details for.
     * @return Information on the particular session.
     */
    @WampProcedure("wamp.session.get")
    CompletableFuture<WampSessionDetails> getSessionDetailsAsync(long sessionId);
}
```

```java
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

@JsonIgnoreProperties(ignoreUnknown = true)
public class WampSessionDetails {
    @JsonProperty("authprovider")
    public String authProvider;

    @JsonProperty("authid")
    public String authId;

    @JsonProperty("authrole")
    public String authRole;

    @JsonProperty("authmethod")
    public String authMethod;

    @JsonProperty("session")
    public long session;
}
```

And usage:

```java
IWampSessionDescriptorProxy sessionDescriptorProxy = factory.getCalleeProxy(IWampSessionDescriptorProxy.class);

CompletableFuture<WampSessionDetails> callFuture =
        sessionDescriptorProxy.getSessionDetailsAsync(sessionDetails.sessionID);

callFuture.thenAccept(result ->
        System.out.println(String.format("authid: %s", result.authId)));
```

**Comment by oberstet** [comment]
Hi Elad, sorry for sluggish response - I missed that one.

This is cool, and I fully agree: it would further improve on developer experience.

What you have with WampSharp and the reflection based callee ends up with very clean, nice user code. AutobahnJava is not yet there, but as you sketch out, could follow on a similar path. And I'd be +1 on this.

> btw, Q: what about a "reflection based subscriber"?

**Comment by darkl** [comment]
Hi Tobias, thanks for you response! :)

I am glad you are for this approach.

I didn't try implementing reflection based callee/subscriber yet (eventually they use the same code more or less), because I did not get any response on this issue. I do plan to try implementing it, but this might take me some time.

Elad

**Comment by oberstet** [comment]
There is one more place where this reflection/decorator approach could work: custom exceptions, auto-mapping WAMP app errors to custom Java Exception objects instead of a generic ApplicationError.

AutobahnPython has this decorator based feature for callee/subscriber and custom exceptions ..

**Comment by oberstet** [comment]
FWIW, revisiting this thread after some time, the API proposed would be quite cool and comfortable. And it can be added without breaking existing API, only adding more sugar on top;)

**Comment by darkl** [comment]
I actually already implemented it, and Omer merged it.

Elad

**Comment by oberstet** [comment]
Oh, ok, I missed that one;) cool!!
