### ISSUE TITLE
Handle loss of transport properly

### ISSUE THREAD

**Issue by 0xAliHn** [crossbario/autobahn-java#337]
Getting this error sometimes without any reason like roaming, network switching etc. Even when device just in stationary state:
`connection close, Notification: 5 reason: WebSockets internal error (javax.net.ssl.SSLException: Read error: ssl=0xb7747000: I/O error during system call, Software caused connection abort)`

using `compile 'io.crossbar.autobahn:autobahn-android:17.10.5'`

**Comment by om26er** [comment]
Could you provide the complete log ? This seems to be coming from java internals. How long shall I keep my device idle to reproduce that issue ?

Also are you keeping a wakelock on your device ?

**Comment by ali-augmedix** [comment]
I just received this logs from my application. You should keep your device in active session more than 1 hour. I guess occurring within 1 hour.

Yes, Wakelock is enable.

**Comment by 0xAliHn** [comment]
I just received this logs from my application. You should keep your device in active session more than 1 hour. I guess occurring within 1 hour.

Yes, Wakelock is enable.

**Comment by om26er** [comment]
I will try to reproduce that issue today and see if I can cook up a fix.

**Comment by oberstet** [comment]
The Java internal error should be caught by ABJ, and propagated as a "transport lost" exception to user code.

Keeping WebSocket connections stable in practice means:

- use TLS
- use both router and client initiated WebSocket hearbeating

=> activate WebSocket heartbeating in Crossbar.io

@om26er do we have auto-ping/pong in ABJ already?

further reading: https://stackoverflow.com/a/31345743/884770

**Comment by om26er** [comment]
> @om26er do we have auto-ping/pong in ABJ already?

Yes, its working already, though we can probably add some configuration to it: https://github.com/crossbario/autobahn-java/issues/303

**Comment by oberstet** [comment]
When a transport (underlying a WAMP session) is lost, this should be communicated to user code with a proper exception: `TransportLost`

https://github.com/crossbario/autobahn-java/tree/master/autobahn/src/main/java/io/crossbar/autobahn/wamp/exceptions

**Comment by oberstet** [comment]
cannot reproduce (anymore) .. pls provide a reproducing example if you still run into this ..
