### ISSUE TITLE
Possible bug in CALL message parsing

### ISSUE THREAD

**Issue by smarg120** [crossbario/autobahn-java#339]
In 
https://github.com/crossbario/autobahn-java/blob/master/autobahn/src/main/java/io/crossbar/autobahn/wamp/messages/Call.java

in parse method first line does the validation
MessageUtil.validateMessage(wmsg, MESSAGE_TYPE, "CALL", 4);

according to spec CALL message can be as big a 6 if it has arguments (also code after the validation gets the  arguments by fetching 5-th member)....seems like 4 should be minimal array length, not max length

**Comment by oberstet** [comment]
which it is https://github.com/crossbario/autobahn-java/blob/master/autobahn/src/main/java/io/crossbar/autobahn/wamp/utils/MessageUtil.java#L32

**Comment by smarg120** [comment]
its not..the call goes to here https://github.com/crossbario/autobahn-java/blob/master/autobahn/src/main/java/io/crossbar/autobahn/wamp/utils/MessageUtil.java#L56

in this case 4 also max length...i cant send call messages with arguments - the validation fails..

**Comment by smarg120** [comment]
the correct validation should be MessageUtil.validateMessage(wmsg, Call.MESSAGE_TYPE, "CALL", 4, 6); or something...

**Comment by oberstet** [comment]
oh, you are right. overlooked the overload, sorry. however, this code is never executed anyways, since AutobahnJava will never _receive_ a CALL message (only a router will).

**Comment by oberstet** [comment]
@om26er we could remove some message classes completely, as a WAMP client won't ever receive those, but we could leave them in for "completeness" also. I don't feel strongly about either..

**Comment by smarg120** [comment]
actually i am playing with such router implementation and it helps to have WAMP messages parsing code in place (consider the case where some router imlpementation is also a client and can use ABJ for both Session/Client and WAMP for raw message parsing...

**Comment by oberstet** [comment]
supporting router implementations on top of ABJ is a non-goal / out of scope for ABJ and embedding routers into apps is sth I wouldn't do in general.

anyways, if you care, PRs are welcome! =)
