### ISSUE TITLE
Error:Error converting bytecode to dex: Cause: Dex cannot parse version 52 byte code.

### ISSUE THREAD

**Issue by rmanaugmedix** [crossbario/autobahn-java#341]
@om26er,  
I can't compile the library in Android (API19). As autobahn is using java 8 features we tried retrolambda to support java 8. But right now we are getting following error. Any solution?
```
Error:Error converting bytecode to dex:
Cause: Dex cannot parse version 52 byte code.
This is caused by library dependencies that have been compiled using Java 8 or above.
If you are using the 'java' gradle plugin in a library submodule add 
targetCompatibility = '1.7'
sourceCompatibility = '1.7'
to that submodule's build.gradle file.
...while parsing io/crossbar/autobahn/BuildConfig.class
```

**Comment by om26er** [comment]
@rmanaugmedix We use more Java8 features than just lambdas, so this won't work.

If you really want to use the library on older Androids, you will have to build it from source yourself. Clone autobahn-java and run the `enable_old_androids.sh`, then just compile the project through Android Studio.

as a side note: Lambdas are now available on Android Studio 3.0, so you don't need retrolambda. Just add below in your build.gradle
```
compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
}
```
