### ISSUE TITLE
Expose Jackson features to control AutoDetect

### ISSUE THREAD

**Issue by ocroquette** [crossbario/autobahn-java#35]
Some classes in 3rd party library I use deviate from the JavaBeans convention that Jackson expects by default.
AutobahnAndroid currently doesn't export the corresponding features in Jackson to control this, which makes the whole very cumbersome.

http://wiki.fasterxml.com/JacksonFeatureAutoDetect
http://www.cowtowncoder.com/blog/archives/2011/02/entry_443.html
http://www.cowtowncoder.com/blog/archives/2011/03/entry_448.html

A great solution would be to expose ObjectMapper.setVisibility.

**Comment by oberstet** [comment]
maybe we should expose the whole jackson object mapper used internally to allow such tweaking, yeah.

**Comment by oberstet** [comment]
The ObjectMapper instance used for WAMP serialization is now public https://github.com/crossbario/autobahn-java/blob/master/autobahn/src/main/java/io/crossbar/autobahn/wamp/serializers/CBORSerializer.java#L27
