### ISSUE TITLE
Building library with enable_old_androids hangs, and 17.10.5 fails to build on Android minSdk 24

### ISSUE THREAD

**Issue by etbusch** [crossbario/autobahn-java#351]
Hello All,

I need to be able to target SDK 24 with this library, and the version on maven fails to build 17.10.5 targeting SDK 24 with the following error message:
```
Error:com.android.builder.dexing.DexArchiveBuilderException: Failed to process /home/eric/.gradle/caches/transforms-1/files-1.1/autobahn-android-17.10.5.aar/66e0c6ba1209dfcc58b2763b3d18f0ec/jars/classes.jar
Error:com.android.builder.dexing.DexArchiveBuilderException: Error while dexing io/crossbar/autobahn/wamp/Client.class
Error:com.android.dx.cf.code.SimException: invalid opcode ba (invokedynamic requires --min-sdk-version >= 26)
Error:Execution failed for task ':app:transformClassesWithDexBuilderForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process /home/eric/.gradle/caches/transforms-1/files-1.1/autobahn-android-17.10.5.aar/66e0c6ba1209dfcc58b2763b3d18f0ec/jars/classes.jar
```

So I grabbed the source and attempted to build the jar after running the enable_old_androids.sh script.
The build hangs at the below step:
```shell
eric@eric-laptop ~/w/w/autobahn-java> ./enable_old_androids.sh 
eric@eric-laptop ~/w/w/autobahn-java> make build_autobahn
docker run -it --rm \
	-v /home/eric/workspace/wsu/autobahn-java:/workspace \
	crossbario/autobahn-java:netty \
	gradle -PbuildPlatform=netty distZip
Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details
<-------------> 0% EXECUTING [4m 23s]
> :autobahn:compileJava > Resolve dependencies :autobahn:compileClasspath > streamsupport-cfuture-1.5.6.pom
```
Any advice would be appreciated.

**Comment by om26er** [comment]
> Any advice would be appreciated.

I just pulled the latest source code, ran `enable_old_androids.sh` and then `make build_autobahn`, it worked just fine.

Maybe the issue you are seeing is related to your internet/firewall ?

**Comment by etbusch** [comment]
That was it, my local docker doesn't like my network settings. Building on another machine was successful. Thanks!

Do you happen to know why the Android build is asking for SDK 26 from the maven repo?

**Comment by om26er** [comment]
> Do you happen to know why the Android build is asking for SDK 26 from the maven repo?

We are compiling with SDK 26, though the minimal supported by the library is SDK 24.

**Comment by etbusch** [comment]
Ah, I needed the following in my gradle android compile options:
```
android {
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
```
