### ISSUE TITLE
Unsubscribe from a topic

### ISSUE THREAD

**Issue by om26er** [crossbario/autobahn-java#352]
Currently there is no way to unsubscribe a topic. We probably need to implement that.

one use case for that is to conserve mobile data usage i.e. only receive events when required.

@oberstet thoughts ?

**Comment by oberstet** [comment]
yeah, unsubscribing from a topic is sth that WAMP provides.

both ABJS and ABPy are actually returning a subscription _object_ when subscribing, and use that to unsubscribe:

* https://github.com/crossbario/autobahn-js/blob/master/lib/session.js#L122
* https://github.com/crossbario/autobahn-python/blob/master/autobahn/wamp/protocol.py#L1365
* https://github.com/crossbario/autobahn-python/blob/master/autobahn/wamp/request.py#L70

**Comment by om26er** [comment]
landed via https://github.com/crossbario/autobahn-java/pull/353
