### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by darkl** [crossbario/autobahn-java#354]
I'm using IntelliJ, and I'm having a hard time building this project. Can you please write instructions how to build it using IntelliJ? Including instructions for dummies, for instance what file am I supposed to open and what buttons am I supposed to click.

I wanted to start working on a pull request related to reflection based roles, but I couldn't make this project compile. Probably some android related SDKs aren't installed on my machine, but I'm not sure which (installed Android Studio in order to install the common tooling).

Thanks,
Elad

**Comment by oberstet** [comment]
@darkl do you want to build for Netty (server stuff) or for Android? for the former, recommendation is using our Docker toolchain image - however, this also isn't documented=(

https://github.com/crossbario/autobahn-java/blob/master/Makefile#L22

**Comment by darkl** [comment]
For future reference, for building netty locally (without android) using IntelliJ, I ended up using this kind of iml file:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<module type="JAVA_MODULE" version="4">
  <component name="NewModuleRootManager" inherit-compiler-output="true">
    <exclude-output />
    <content url="file://$MODULE_DIR$">
      <sourceFolder url="file://$MODULE_DIR$/src" isTestSource="false" />
    </content>
    <content url="file://$MODULE_DIR$/../../autobahn/src">
      <sourceFolder url="file://$MODULE_DIR$/../../autobahn/src/main/java" isTestSource="false" />
      <excludeFolder url="file://$MODULE_DIR$/../../autobahn/src/main/java/io/crossbar/autobahn/websocket" />
    </content>
    <orderEntry type="inheritedJdk" />
    <orderEntry type="sourceFolder" forTests="false" />
    <orderEntry type="library" exported="" name="com.fasterxml.jackson.core:jackson-databind:2.8.8" level="project" />
    <orderEntry type="library" exported="" name="com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:2.8.8" level="project" />
    <orderEntry type="library" exported="" name="org.msgpack:jackson-dataformat-msgpack:0.8.13" level="project" />
    <orderEntry type="library" exported="" name="com.github.joshjdevl.libsodiumjni:libsodium-jni:1.0.7" level="project" />
    <orderEntry type="library" exported="" name="io.netty:netty-codec-http:4.1.2.Final" level="project" />
    <orderEntry type="library" exported="" name="io.netty:netty-handler:4.1.2.Final" level="project" />
    <orderEntry type="library" exported="" name="com.fasterxml.jackson.core:jackson-core:2.8.8" level="project" />
  </component>
</module>
```
I also had to manually delete locally ABALogger.java and AndroidWebSocket.Java.

Hopefully this would help IntelliJ newbies like me, and hopefully more experienced IntelliJ users could explain what is the appropriate way of doing these things.

Elad

**Comment by oberstet** [comment]
@darkl Glad you figured it out;) This Java build stuff can be unwieldy. So yeah, definitely sth for the docs!

**Comment by oberstet** [comment]
We should have a section in the README.md that explains

- how to **build apps** for Netty using our toolchain Docker images (including building those yourself)
- how to **build apps** for Android

Then we could have an appended subsection which collects above findings: how to build apps for Netty using IntelliJ .. and directly (not using our toolchain images).

**Comment by om26er** [comment]
> how to build apps for Android

That's very simple, the README.md currently contains a maven line, that what android developers use to import a library in their project. So for Android its just "add the library and start writing your code".

I think this issue initially was about building the project itself, which again, for Android is very simple: Just import the project in Android Studio, it will automatically download all the dependencies and you are good to start changing the code.

So we mainly need to document
 * How to build Netty version using cli
 * How to build Android version using Android Studio.

**Comment by om26er** [comment]
Here is a PR https://github.com/crossbario/autobahn-java/pull/378

**Comment by oberstet** [comment]
How do I build _apps_ eg on Netty?
