### ISSUE TITLE
onTextMessage() not be called

### ISSUE THREAD

**Issue by manza7014** [crossbario/autobahn-java#357]
when i connectd to sever,i can received message,but when i lost connect and reconnect again successfully,onTextMessage() method cannot be called,what"s wrong!!! when i restart app again,onTgextMessage() can be called normally.tks in advance.

**Comment by manza7014** [comment]
i am not so clear to the answer in#61

**Comment by manza7014** [comment]
i am not so clear to the answer in#61"permanent Ping in 5 minutes to fix my problem!!!"

**Comment by filipefreitas82** [comment]
I don't know if this is related, whenever I disconnect and reconnect back (using ticket auth)  I get this in my server:

**alert      [Thruway\Transport\RatchetTransportProvider 3623] Exception occurred during onMessage: Hello message sent to authentication manager when there is already authentication details attached.**

To fix this I had to reset my client session onDisconnectCallback()
