### ISSUE TITLE
onclose not called if network is disconnected

### ISSUE THREAD

**Issue by sonicfafe** [crossbario/autobahn-java#36]
in android 4.0 is plugged and lost connection to the socket does not try to reconnect or notifies the OnClose....  also the isConnected returns true, the ee sendTextMessage does not send the Feedback but also does not return any error .... some solution? how can I test connectivity from socket?

apparently on androd 4.2.2 and 2.3.7 works, so the connection is lost the authobehn notifies the onClose

thanks

**Comment by ingcaratozzolo** [comment]
Are there news about this problem? The call to onClose is successful with a device with Android 4.4.2 kitkat; instead of a device with Android 5.0.1 lollipop the problem persists.

**Comment by oberstet** [comment]
Detecting loss of a WS connection depends on https://github.com/crossbario/autobahn-android/issues/32 for the general case. 

But of course, `onClose` should be called .. needs investigation.

**Comment by om26er** [comment]
This is probably related to https://github.com/crossbario/autobahn-java/issues/238 for which a fix is already proposed. Though its only relevant to Netty based impl.

**Comment by om26er** [comment]
fixed by https://github.com/crossbario/autobahn-java/pull/287
