### ISSUE TITLE
Releases of JARs and release documentation

### ISSUE THREAD

**Issue by klausmyrseth** [crossbario/autobahn-java#362]
After a bit of searching i found https://mvnrepository.com/artifact/io.crossbar.autobahn/autobahn-java/17.10.5

But you need to document where you publish versions to make it a bit easier to get going ;)

take a look at: https://jitpack.io/#crossbario/autobahn-java this is the goto to check when nothing else is published, all failed builds.

Please make it clearer in the README.md where you find the jar files :)

**Comment by oberstet** [comment]
Am 12.02.2018 um 10:48 schrieb Klaus Myrseth:
> Cant really find anything, would love to test out autobahn for java but I need to have repo managed files for that.
> 
> take a look at: https://jitpack.io/#crossbario/autobahn-java this is the closest i found a repo with autobahn in but sadly it will not build and deploy.
> 
> Please either document where it is or deploy for people to use ^^ 

pls have a look at the docker based toolchain images and use thereof:

https://github.com/crossbario/autobahn-java/blob/master/Makefile#L22

**Comment by om26er** [comment]
> Please make it clearer in the README.md where you find the jar files :)

Thanks for the link to jitpack.io -- Can you please propose a change to README.md and we can continue the discussion regarding improvements there ?

**Comment by klausmyrseth** [comment]
Maby somthing like this:

```
diff --git a/README.md b/README.md
index 72b927e..b5b07f0 100644
--- a/README.md
+++ b/README.md
@@ -39,6 +39,22 @@ and finally
 
 The code in demo-gallery contains some examples on how to use the autobahn library, it also contains convenience methods to use. Below is a basic set of code examples showing all 4 WAMP actions.
 
+### Include Autobahn in your code:
+To use Autobahn in your code as a library you find the dependencies in the central maven repository.
+
+Add the following to your build.gradle dependencies
+```gradle
+compile group: 'io.crossbar.autobahn', name: 'autobahn-java', version: '17.10.5'
+```
+
+Or the following to your maven file.
+```maven
+<dependency>
+    <groupId>io.crossbar.autobahn</groupId>
+    <artifactId>autobahn-java</artifactId>
+    <version>17.10.5</version>
+</dependency>
+```
 ### Subscribe to a topic
 
 ```java
```

**Comment by oberstet** [comment]
So how could we release a new version of ABJ? As I currently look at this, here is what we could aim for:

1. release jars on github (https://blog.github.com/2013-07-02-release-your-software/)
2. publish the jars to mvn (and possibly jitpack)
3. release docker toolchain images

Those steps should be targets in the Makefile.

A release now involves a number of steps, but that is ok for now:

* tag the release
* above
* generate/publish docs
* ...

This process, of how doing a release should also be written down in the docs, so we have one place to refer to.

**Comment by klausmyrseth** [comment]
Have you considered gradle or mvn instead of make? it would do release management quite a bit easier, especially publications against the repositories you want to publish to.

**Comment by oberstet** [comment]
We are already using gradle. What I am referring to is the top-level helper Makefile, and I like that to be make, not some fancy language specific tool. `make publish` should do the right thing, regardless in which Autobahn project I am currently in. As in, `make publish` is trivial enough for me to remember ...

**Comment by om26er** [comment]
For how to install: https://github.com/crossbario/autobahn-java/pull/370
