### ISSUE TITLE
Parsing bug in Event  Long/Integer

### ISSUE THREAD

**Issue by ralscha** [crossbario/autobahn-java#363]
There is a parsing bug in the io.crossbar.autobahn.wamp.messages.Event parse method.

```java
    public static Event parse(List<Object> wmsg) {
        MessageUtil.validateMessage(wmsg, MESSAGE_TYPE, "EVENT", 3, 6);
        long subscription = (long) wmsg.get(1);
        long publication = (long) wmsg.get(2);
```
The code expects the subscription id to be a long but this can be an Integer.
The reason for that is the jackson parser deserializes numbers into Integers if the value fits into the range of an Integer.

In my example the Broker sends back a subscription id of 2. According to the specification this is a valid value.

All these identifiers can be Integers and Longs (if the number does not fit into an Integer)
>    1.  Sessions (_global scope_)
>    2.  Publications (_global scope_)
>    3.  Subscriptions (_router scope_)
>    4.  Registrations (_router scope_)
>    5.  Requests (_session scope_)
>    These are identified in WAMP using IDs that are integers between
>    (inclusive) *0* and *2^53* (9007199254740992):

A solution is to use the MessageUtil.parseRequestID method like you do in the Unregister message
```
    public static Event parse(List<Object> wmsg) {
        MessageUtil.validateMessage(wmsg, MESSAGE_TYPE, "EVENT", 3, 6);
        long subscription = MessageUtil.parseRequestID(wmsg.get(1));
        long publication = MessageUtil.parseRequestID(wmsg.get(2));
```

Another  solution would be to configure Jackson to always deserialize numbers into longs (since Jackson 2.6)

```java
    public ISerializer(JsonFactory factor) {
        mapper = new ObjectMapper(factor);
        mapper.enable(DeserializationFeature.USE_LONG_FOR_INTS);
    }
```

But then you have the problem in the method Session.onMessage. The cast of the messageType no longer works because it is a Long

```java
    @Override
    public void onMessage(byte[] payload, boolean isBinary) throws Exception {
        // transform bytes to raw message:
        List<Object> rawMessage = mSerializer.unserialize(payload, isBinary);

        // transform raw message to typed message:
        try {
            int messageType = (int) rawMessage.get(0);
```

**Comment by oberstet** [comment]
> Another solution would be to configure Jackson to always deserialize numbers into longs (since Jackson 2.6)

Yes, we should do that. Require Jackson 2.6+ and enforce deserialization of all WAMP IDs as longs-
