### ISSUE TITLE
Thread WebSocketConnector remains active

### ISSUE THREAD

**Issue by Maleandr** [crossbario/autobahn-java#37]
After calling disconnect() thread WebSocketConnector remains active and dont disappear from application thread pool. Calling next connect() cause spawn new thread, so they are stacking in pool. Tested on Android 4.1.2

**Comment by oberstet** [comment]
We should double check that this is really gone ..

**Comment by om26er** [comment]
I have looked around the code and verified with a few experiments that this issue is not happening. Also the code suggests that this issue should not happen as there is no codepath that could cause the run() to not return.
