### ISSUE TITLE
Release 18.3.1

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-java#381]
Released via https://github.com/crossbario/autobahn-java/pull/382

The Docker toolchain image is published. Maven/gradle not .. as the `Makefile` requires tools on the  host - rather than from inside a Docker image ..

So we still need to publish to mvn/gradle @om26er

**Comment by noman-augmedix** [comment]
@oberstet did you publish 18.3.1 to mvn/gradle? According to the comment by @om26er in the [commit](https://github.com/crossbario/autobahn-java/commit/2e18e7eac3fff1ee27655566631a2bdefc41e0a0) I am trying to use **autobahn-android-18.3.1**  by gradle dependency in my project, but unfortunately my app getting crash, but if I use **autobahn-android-17.10.5** then it's working fine. Also exporting aar file of 18.3.1 from Android Studio is working fine.
Do you have any update regarding this issue?

**Comment by om26er** [comment]
> Do you have any update regarding this issue?

let me try that myself and I'll get back to you.

**Comment by om26er** [comment]
@noman-augmedix I published the release and I am currently working on an Android app that is using the latest version of that library. Could you please show the error messages you seeing.

**Comment by noman-augmedix** [comment]
@om26er here is the error message, it seems webRTC related issue but it occurred if I use the gradle dependency like as following.
> compile 'io.crossbar.autobahn:autobahn-android:18.3.1'

But if I use the dependency as following, no error occurred.
> compile files('libs/autobahn-android-18.3.1.aar')
```
03-28 16:25:31.899 25443-26261/<<package>> E/art: No implementation found for void org.webrtc.PeerConnectionFactory.initializeFieldTrials(java.lang.String) (tried Java_org_webrtc_PeerConnectionFactory_initializeFieldTrials and Java_org_webrtc_PeerConnectionFactory_initializeFieldTrials__Ljava_lang_String_2)
    
    --------- beginning of crash
03-28 16:25:31.900 25443-26261/<<package>> E/AndroidRuntime: FATAL EXCEPTION: PEER_CONNECTION_HANDLER
    Process: <<package>>, PID: 25443
    java.lang.UnsatisfiedLinkError: No implementation found for void org.webrtc.PeerConnectionFactory.initializeFieldTrials(java.lang.String) (tried Java_org_webrtc_PeerConnectionFactory_initializeFieldTrials and Java_org_webrtc_PeerConnectionFactory_initializeFieldTrials__Ljava_lang_String_2)
        at org.webrtc.PeerConnectionFactory.initializeFieldTrials(Native Method)
        at kosuna.webrtcsdk.webrtcclient.impl.WebRTCClient$PeerConnectionHandler.createOrInitializePCFactoryAndAudioManager(WebRTCClient.java:283)
        at kosuna.webrtcsdk.webrtcclient.impl.WebRTCClient$PeerConnectionHandler.handleMessage(WebRTCClient.java:222)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by om26er** [comment]
This is most probably Android Studio acting up, 'Invalidate Caches & Restart' in Android Studio's File menu

**Comment by noman-augmedix** [comment]
> 'Invalidate Caches & Restart' in Android Studio's File menu

Followed it, but no benefit.
Do you have any idea why the library is not available in the following link?
[https://mvnrepository.com/artifact/io.crossbar.autobahn/autobahn-android/18.3.1](https://mvnrepository.com/artifact/io.crossbar.autobahn/autobahn-android/18.3.1)

**Comment by om26er** [comment]
I am not really sure, probably that website didn't update or have an issue because maven central has the latest release already: http://central.maven.org/maven2/io/crossbar/autobahn/autobahn-android/18.3.1

**Comment by noman-augmedix** [comment]
I did already, It seems to me only difference is still no update in [https://mvnrepository.com/artifact/io.crossbar.autobahn/autobahn-android](https://mvnrepository.com/artifact/io.crossbar.autobahn/autobahn-android) for 18.3.1. I believe, I have to wait for the update in mvnrepository.

**Comment by oberstet** [comment]
the release is published - also to mvn (http://central.maven.org/maven2/io/crossbar/autobahn/autobahn-android/18.3.1/):

```
io/crossbar/autobahn/autobahn-android/18.3.1

../
autobahn-android-18.3.1-javadoc.jar               2018-03-23 09:47    428755      
autobahn-android-18.3.1-javadoc.jar.asc           2018-03-23 09:47       821      
autobahn-android-18.3.1-javadoc.jar.md5           2018-03-23 09:47        32      
autobahn-android-18.3.1-javadoc.jar.sha1          2018-03-23 09:47        40      
autobahn-android-18.3.1-sources.jar               2018-03-23 09:47    105766      
autobahn-android-18.3.1-sources.jar.asc           2018-03-23 09:47       821      
autobahn-android-18.3.1-sources.jar.md5           2018-03-23 09:47        32      
autobahn-android-18.3.1-sources.jar.sha1          2018-03-23 09:47        40      
autobahn-android-18.3.1.aar                       2018-03-23 09:47    137530      
autobahn-android-18.3.1.aar.asc                   2018-03-23 09:47       821      
autobahn-android-18.3.1.aar.md5                   2018-03-23 09:47        32      
autobahn-android-18.3.1.aar.sha1                  2018-03-23 09:47        40      
autobahn-android-18.3.1.pom                       2018-03-23 09:47      1986      
autobahn-android-18.3.1.pom.asc                   2018-03-23 09:47       821      
autobahn-android-18.3.1.pom.md5                   2018-03-23 09:47        32      
autobahn-android-18.3.1.pom.sha1                  2018-03-23 09:47        40      
```
