### ISSUE TITLE
WAMP: Expose transport disconnect reason ?

### ISSUE THREAD

**Issue by om26er** [crossbario/autobahn-java#389]
Currently it becomes a challenge to distinguish the cause of disconnect of a WAMP session.

Our current onDisconnect listener looks like this https://github.com/crossbario/autobahn-java/blob/master/autobahn/src/main/java/io/crossbar/autobahn/wamp/interfaces/ISession.java#L758

@oberstet do you think we can expend that to include the disconnect reason or would that be exposing WebSocket internals to WAMP public API ?

**Comment by oberstet** [comment]
When the transport underlying a session is lost, two things should happen:

* `onLeave` fired with `reason` https://github.com/crossbario/autobahn-python/blob/master/autobahn/wamp/types.py#L390
* `onDisconnect` fired with `wasClean == False`

When a session actively leaves and closes the transport, the `onLeave` should fire with https://github.com/crossbario/autobahn-python/blob/master/autobahn/wamp/types.py#L389 and `onDisconnect` with `wasClean == True`.

**Comment by om26er** [comment]
@oberstet I have a PR for what you suggested above https://github.com/crossbario/autobahn-java/pull/390

**Comment by oberstet** [comment]
fixed via #390
