### ISSUE TITLE
NullPointerException in Session.onLeave() 

### ISSUE THREAD

**Issue by jellisgwn** [crossbario/autobahn-java#412]
When crossbar is shutdown with an Autobahn Java client connected the `CloseDetails` passed to `onLeave()` is null: 
```
    public void onLeave(CloseDetails details) {
        if (this.mState != 1) {
            LOGGER.d("onLeave(), reason=" + details.reason);
```
The call to `LOGGER.d` then obviously throws an NPE, and no handlers are called. The call to `onLeave()` comes from `NettyWebSocketClientHandler.channelInactive()`, which is being called from Netty.

**Comment by jellisgwn** [comment]
You could just create a `CloseDetails` with a reason such as `wamp.close.transport_inactive`. It doesn't look like Netty is providing anything useful that you could pass on during the callback...

**Comment by om26er** [comment]
Proposed a fix here https://github.com/crossbario/autobahn-java/pull/414
