### ISSUE TITLE
Failure of Client.connect() is not surfaced

### ISSUE THREAD

**Issue by jellisgwn** [crossbario/autobahn-java#417]
If a call to Client.connect() fails (for example crossbar is not listening at the given address / port) the failure is not returned to the caller:
```
        CompletableFuture.runAsync(() -> {
            try {
                mTransports.get(0).connect(mSession, options);
            } catch (Exception e) {
                throw new CompletionException(e);
            }
        }, getExecutor());
```
the `CompletableFuture` returned from the call to `runAsync()` is discarded, and therefore the caller has no means to determine if the call to the transport completed normally.

Should the result be combined with the `ExitInfo` that is being returned?

**Edit:** maybe something like this:
```
        CompletableFuture.runAsync(() -> {
            try {
                mTransports.get(0).connect(mSession, options);
            } catch (Exception e) {
                exitFuture.completeExceptionally(e);
            }
        }, getExecutor());
```
another alternatives would be adding a new `onConnectionFailure` event to the `Session`. Not sure which is more appropriate for the model.

**Comment by om26er** [comment]
I just confirmed that to be Netty specific issue, looking into this now.

**Comment by om26er** [comment]
@jellisgwn I have a fix for that here https://github.com/crossbario/autobahn-java/issues/417 -- please give that a try, if you are able to.

**Comment by jellisgwn** [comment]
@om26er i've tested the change to call `exitFuture.completeExceptionally(e);` instead of throwing in my local build. It works as expected.

Note sure about calling `onDisconnect` when never having connected. Is that how this situation is handled in other Autobahn implementations?

Thinking about it... my concern is being able to detect that the Session is not connected, and begin attempts to reconnect, and having `onDisconnect` called gives me a single place to do that. Cool.

I'll make those changes locally, see how it all fits together, and report back.
