### ISSUE TITLE
Remove Android dependency from WebSocket implementation

### ISSUE THREAD

**Issue by om26er** [crossbario/autobahn-java#419]
* Make the implementation modular to support multiple environments

Our current dependence on Android is for messaging between Reader/Writer WebSocket threads and notifying the main(UI) thread about those. With refactoring we can make the messaging modular, allowing for use on both Android and non-Android platforms.

Advantages include minimizing the number of bugs and the reduction of maintenance burden of the Netty based WAMP transport.

This is just a proposal, a place to gather advantages/disadvantages. If given an architectural "approval", I can try making time from my personal schedule as well.

**Comment by oberstet** [comment]
we have other fish to fry;) seriously, our own WebSocket implementation for Android does work great - as does Netty/WebSocket. And both are completely hidden (apart from initial connection setup, which is fine) from the user eg when writing a WAMP app. won't fix for now
