### ISSUE TITLE
Autobahn-Java on Android Connection Timeout

### ISSUE THREAD

**Issue by jurjen96** [crossbario/autobahn-java#420]
When we try to set up a WAMP connection between Android Java (using autobahn-java) and the Nexus router, we receive the following output from the router:

```
2018/08/13 10:23:54 Error attaching to router: did not receive HELLO: timeout waiting for message
```

In the Android console:

```
W/art: Method processed more than once: boolean io.crossbar.autobahn.websocket.WebSocketReader.processHandshake()
W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
                  at io.crossbar.autobahn.wamp.transports.AndroidWebSocket.initializeSerializer(AndroidWebSocket.java:160)
W/System.err:     at io.crossbar.autobahn.wamp.transports.AndroidWebSocket.access$100(AndroidWebSocket.java:32)
                  at io.crossbar.autobahn.wamp.transports.AndroidWebSocket$1.onConnect(AndroidWebSocket.java:86)
                  at io.crossbar.autobahn.websocket.WebSocketConnection$2.handleMessage(WebSocketConnection.java:648)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
                  at android.os.Looper.loop(Looper.java:148)
                  at android.app.ActivityThread.main(ActivityThread.java:5509)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:772)
                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:662)
```
We received the error message of 'timeout waiting for message' after 5 seconds when the Android application tries to connect to the router. When we use the Crossbar router, we get a successful connection between the session and the router. Could you guys have a look at this issue? We are also using autobahn-python in combination with the Nexus router, and that one works great. 

Initially, I started an issue on the Nexus router side, for side reference: [gammazero/nexus#143](https://github.com/gammazero/nexus/issues/143) has been moved to [gammazero/nexus#146](https://github.com/gammazero/nexus/issues/146)

**Comment by yashovardhan99** [comment]
@oberstet I am facing the same issue. We have a server deployed on Heroku and trying to connect to it through android, I get the same error that they got. Is there a fix I am missing somewhere?

**Comment by om26er** [comment]
@yashovardhan99 I followed through this specific issue with Nexus router and it seems its no longer happening https://github.com/gammazero/nexus/issues/146#issuecomment-463051456

Could you please report a new issue and we can start the conversation there ?

**Comment by yashovardhan99** [comment]
@om26er I have found the root cause of this issue (at least for my case). Please see #432
