### ISSUE TITLE
onMessage catch swallows the exception on empty messages

### ISSUE THREAD

**Issue by animaonline** [crossbario/autobahn-java#421]
This is easily reproduced, whenever the server returns an empty message, messageKlass.getMethod throws an exception, leaving the CompletableFuture.whenComplete hanging.

Is there a way around this bug?

**Comment by animaonline** [comment]
Well, I could provide an example, but the issue would still be there, the exceptions should not be swallowed.

As for the "empty message", it's basically a message that does not have any args (kw and regular ones)

**Comment by oberstet** [comment]
as said, what router etc. is important to track this down. otherwise: PRs are welcome;)

**Comment by animaonline** [comment]
We're using Crossbar.io, I suppose that's the router? :)

**Comment by oberstet** [comment]
cannot reproduce
