### ISSUE TITLE
Create new Maven release

### ISSUE THREAD

**Issue by jellisgwn** [crossbario/autobahn-java#429]
Some bugs were fixed last year that haven't made it out into a release. Can a new release be pushed to Maven?

**Comment by jellisgwn** [comment]
Hi @om26er, raised this with @oberstet in the Gitter Chat and he suggested coming to you.

**Comment by om26er** [comment]
@jellisgwn yes, I'll look into this, curious to know, is there a specific bug fix you are interested in ?

**Comment by jellisgwn** [comment]
@om26er thanks. yep, specifically these:

https://github.com/crossbario/autobahn-java/issues/412
https://github.com/crossbario/autobahn-java/issues/417

**Comment by oberstet** [comment]
@om26er any news?

**Comment by om26er** [comment]
@oberstet 19.3.1 is now published, should take a few hours for it to sync everywhere. Will do release announcement later.

**Comment by oberstet** [comment]
oh, cool! thanks! 

> guess that would also make up for a nice announcement on the new Discourse forum. which reminds me: we should close gitter, add an IRC header and write an announcment on the G mailing lists and close those too (or archive or whatever). I think the "one place to discuss" push that you initiated is an important one .. together with the documentation overhaul, which is also already in progress or launched now. which is great=)
