### ISSUE TITLE
Support NaCl SealedBox

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-java#431]
This issue is about the first step of supporting WAMP-cryptosign and XBR in AutobahnJava, which is integrate a NaCl library to that we can implement the former.

Ultimately, we want an ABJ equivalent of the code here:

* https://github.com/crossbario/autobahn-python/blob/master/autobahn/wamp/cryptosign.py
* https://github.com/xbr/xbr-protocol/blob/master/xbr/_buyer.py
* https://github.com/xbr/xbr-protocol/blob/master/xbr/_seller.py

---

I've looked at some of the libraries from here https://download.libsodium.org/doc/bindings_for_other_languages/, and spent a bit more time looking into lazysodium, which I had a good impression:

* https://github.com/terl/lazysodium-android
* https://github.com/terl/lazysodium-java
* https://docs.lazycode.co/lazysodium/installation#android
* https://github.com/terl/lazysodium-java/tree/master/src/main/java/com/goterl/lazycode/lazysodium
* https://github.com/terl/lazysodium-java/tree/master/src/main/java/com/goterl/lazycode/lazysodium/interfaces

The other library that I looked at:

* https://github.com/ConsenSys/cava
* https://consensys.github.io/cava/docs/java/latest/net/consensys/cava/crypto/sodium/package-summary.html

---

In WAMP-cryptosign and XBR we need:

* `nacl.signing.SigningKey`
* `nacl.secret.SecretBox`
* `nacl.public.SealedBox`

and while I've seen `SecretBox` support in lazysodium and cava, not sure about `SealedBox` .. haven't seen that one.

In which case we would need to work with upstream to get support for that into the lib ..

@om26er what do you think? I _think_ you once looked into NaCl libraries also / already .. not sure?

**Comment by om26er** [comment]
> @om26er what do you think? I _think_ you once looked into NaCl libraries also / already .. not sure?

yes, we do support CryptoSign in autobahn-java today, using https://github.com/joshjdevl/libsodium-jni, I just peaked into its source and it seems it doesn't implement SealedBox as well.

Regarding `lazysodium`, it seems fine, though is maintained by a single person, so wonder what happens if the person loses interest.

Here is our CryptosignAuth impl: https://github.com/crossbario/autobahn-java/blob/master/autobahn/src/main/java/io/crossbar/autobahn/wamp/auth/CryptosignAuth.java#L18

**Comment by oberstet** [comment]
ahhh, right .. I forgot! cool=) so we have a NaCl library already integrated, and we only need to find out how to use `SealedBox` - or how work with upstream of https://github.com/joshjdevl/libsodium-jni to support it.

**Comment by om26er** [comment]
FYI, the upstream proposal lives here https://github.com/joshjdevl/libsodium-jni/pull/127

**Comment by om26er** [comment]
Closing this, we do have SealedBox in now. Also have some of the XBR stuff as well.
