### ISSUE TITLE
XBR simple seller

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-java#437]
ABJ should support XBR (in general), and provide the analogue of the Python XBR library simple XBR seller for easy use in applications:

* https://github.com/xbr/xbr-protocol/blob/master/xbr/_seller.py

**Comment by om26er** [comment]
Starting on this now...

**Comment by om26er** [comment]
Seller is done in principle, any gaps will be addressed on need basis when working on the Markets App.
