### ISSUE TITLE
XBR simple buyer

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-java#438]
ABJ should support XBR (in general), and provide the analogue of the Python XBR library simple XBR buyer for easy use in applications:

* https://github.com/xbr/xbr-protocol/blob/master/xbr/_buyer.py

**Comment by om26er** [comment]
So I forgot that I had implemented that partially (or mostly), would need to clean up and fix minor gaps here and there to call it "done" https://github.com/crossbario/autobahn-java/blob/master/autobahn/src/main/java/xbr/network/SimpleBuyer.java

**Comment by oberstet** [comment]
ah, cool=) sounds good: cleanup etc ... let's keep the issue open until then

**Comment by om26er** [comment]
The buy is now working and landed https://github.com/crossbario/autobahn-java/pull/470 -- For any improvements, we'll open new issues
