### ISSUE TITLE
Configuration of MsgPack with Autobahn Java

### ISSUE THREAD

**Issue by robfra31** [crossbario/autobahn-java#447]
Hello
I would like to know how the configuration of the Serializer (MsgPack or JSON) is made when using Autobahn Java ?
Is it a configuration of my WAMP server (e.g: the Nexus router) or a configuration to do in Autobahn ?
I am connecting my class to the WAMP server (which is a Nexus WAMP) with:

public void main() {
    Session session = new Session();
    session.addOnJoinListener(this::demonstrateSubscribe);
    session.addOnJoinListener(this::demonstratePublish);
    session.addOnJoinListener(this::demonstrateCall);
    session.addOnJoinListener(this::demonstrateRegister);
    Client client = new Client(session, url, realm);
    CompletableFuture<ExitInfo> exitInfoCompletableFuture = client.connect();
}

But I don't see where is it possible to configure the serializer that I will use when I am doing a simple: 
`session.publish("com.myapp.hello", "Hi!");`

Does my "Hi!" string is serialized in MsgPack or in JSON ?

Regards,

**Comment by om26er** [comment]
The client library (autobahn) sends a list of serializers that it supports, the router then decides which serializer it wants to select and replies that to the client on the initial connect.

Currently autobahn-java has a default list of supported serializers that itoffers](https://github.com/crossbario/autobahn-java/blob/master/autobahn/src/main/java/io/crossbar/autobahn/wamp/transports/AndroidWebSocket.java#L35) to the router. We currently don't have a way to enforce a specific serializer, that something we still need to implement.

Also we use our forum https://forum.crossbar.io/c/autobahn-java for conversations around autobahn and crossbar, please use that for future conversations :-)
