### ISSUE TITLE
Android first connect normal, reconnect interaction only once LOST reason:AutoPing timed out

### ISSUE THREAD

**Issue by zorouyang** [crossbario/autobahn-java#450]
Launch app > connect wss://,  sendMessage and onMessage HB normal.
Background stop the websocket and Resume reconnect again.  just only once send/received message HB. called CONNECTION_LOST reason:AutoPing timed out.

**Comment by om26er** [comment]
Could you please share the code that I could use to reproduce that issue ?

**Comment by zorouyang** [comment]
Thanks for your quick reply.
I found the cause of the problem, and Hb caused the connection to break immediately after opening. Delay returned to normal.
I guess it's the problem that our server handles, which embarrasses me.

Thanks a lot, again.
