### ISSUE TITLE
web3j upstream hasn't released latest version for android

### ISSUE THREAD

**Issue by om26er** [crossbario/autobahn-java#455]
Mainly due to lack of resources they haven't released newer version of web3j-android https://github.com/web3j/web3j/issues/1030

Support for EIP712 was added in versions that are not yet released for android. Need to investigate if we can copy-pasta the required functionality from this PR for now https://github.com/web3j/web3j/pull/911

**Comment by oberstet** [comment]
yeah, agree, if it makes sense, I'm cool with temporarily copying over the bits we need (above PR .. essentially 3 months old;). And once a new release is done upstream, we might eventually use that again ..

**Comment by om26er** [comment]
They had released a new version a while ago and we have been using that since https://github.com/crossbario/autobahn-java/pull/490
