### ISSUE TITLE
Invalid webSocketURL error is ignored at connect

### ISSUE THREAD

**Issue by SergeyLukashevich** [crossbario/autobahn-java#459]
Running client.connect() with a wrong webSocketURL defined for a client doesn't cause an error, as expected.

Example:
```
        var session = new Session();
        var client = new Client(session, "BAD URL", "realm");

        try {
            client.connect().get();
        } catch (Exception e) {
            e.printStackTrace(); // << Never called
        }
```
I see that error is in a method `Client::connect(TransportOptions options)`:

```        CompletableFuture.runAsync(() -> {
            try {
                mTransports.get(0).connect(mSession, options);
            } catch (Exception e) {
                throw new CompletionException(e);
            }
        }, getExecutor());
```
Connection is performed asynhronously, but raised CompletionException is lost, as soon `runAsync`
result is unused.

**Comment by om26er** [comment]
Thanks for reporting this issue, I have verified the bug and understand the cause for it, I will propose a fix for that soon.

**Comment by om26er** [comment]
I have a fix here https://github.com/crossbario/autobahn-java/pull/460

**Comment by om26er** [comment]
> I have verified the bug and understand the cause for it, I will propose a fix for that soon.

Sorry, I wrote too soon, that code path did have an issue that I fixed in https://github.com/crossbario/autobahn-java/pull/460 but its likely different from what you are seeing. Even without the changes that I proposed, I am not able to reproduce the exact issue that you are seeing as I rightfully see the stacktrace.

Could it be a Kotlin oddity ?

**Comment by om26er** [comment]
Here is a Java method that seems to work as expected
```
    private void testConnect() {
        Session session = new Session();
        Client client = new Client(session, "asfdasd", "realm1");
        try {
            client.connect().get();
        } catch (ExecutionException | InterruptedException e) {
            e.printStackTrace();
        }
    }
```

**Comment by SergeyLukashevich** [comment]
Sorry, it's my fault. I'm using the version 18.5.1 that is defined in README.md, not the recent one.
