### ISSUE TITLE
release v20.6.1

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-java#486]

**Comment by jellisgwn** [comment]
It might be good to evaluate #489 before releasing.

**Comment by om26er** [comment]
@jellisgwn 20.6.1 is already released. We could do another release if needed to update those dependencies.

**Comment by jellisgwn** [comment]
@om26er interesting... it hasn't updated the releases page so that wasn't obvious to me.

**Comment by om26er** [comment]
That is indeed interesting, I had pushed the tag https://github.com/crossbario/autobahn-java/releases/tag/v20.6.1 but it indeed didn't get "promoted" as a new release on this page https://github.com/crossbario/autobahn-java/releases. Wonder what could have caused that

**Comment by jellisgwn** [comment]
Not sure. The front page of the project also still shows the latest release as 20.2.1... makes it hard to identify a new release!

**Comment by om26er** [comment]
I have now created a new release manually. Should be good now. For the next version, I will ensure that to not happen again
