### ISSUE TITLE
webSocket,onClose,code3reasonAutoPing timed out.

### ISSUE THREAD

**Issue by Endless-explorer** [crossbario/autobahn-java#494]
连接后没几秒钟就断了

**Comment by Endless-explorer** [comment]
我是Android客户端

**Comment by oberstet** [comment]
sorry, english (or german)?

**Comment by om26er** [comment]
I am going to close this one as we did not hear back from the original reporter, and the information provided in the report even after translation doesn't really help.

**Comment by Endless-explorer** [comment]
i have solved this problem ,thanks for reply
