### ISSUE TITLE
Update XBR Implementation

### ISSUE THREAD

**Issue by om26er** [crossbario/autobahn-java#499]
The XBR implementation in Java needs the same treatment as the JS one.

**Comment by oberstet** [comment]
fwiw, I want to get into ABJ/Java/Android again too;) what dev setup / ide / tools are you using for android/java? what's the "current rage"?

**Comment by om26er** [comment]
> fwiw, I want to get into ABJ/Java/Android again too;) what dev setup / ide / tools are you using for android/java? what's the "current rage"?

That's great to know :+1: 

I use Android Studio to do the development, the good thing about it is that it takes care of installing all the dependencies on its own. if something requires the user input, it will ask for it.

On Ubuntu the easiest way to install Android Studio is through snap (I maintain that ;-)
```
snap install android-studio --classic
```

OTOH: I spent some time trying to fix/improve the XBR impl and have a PR https://github.com/crossbario/autobahn-java/pull/500 -- Still need to fix the Buyer, which I will do tomorrow.

**Comment by oberstet** [comment]
having these notes (plus maybe a couple of more) in ABJ docs would be great!

eg following https://developer.android.com/studio/run/emulator-acceleration?utm_source=android-studio#vm-linux (which is one step the installation asks for - optional):

```
oberstet@intel-nuci7:~$ which android-studio
/snap/bin/android-studio
oberstet@intel-nuci7:~$ sudo apt-get install cpu-checker
[sudo] Passwort für oberstet: 
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
cpu-checker ist schon die neueste Version (0.7-0ubuntu7).
cpu-checker wurde als manuell installiert festgelegt.
Die folgenden Pakete wurden automatisch installiert und werden nicht mehr benötigt:
  libarrow-glib17 libarrow17 libllvm9 linux-headers-4.15.0-112 linux-headers-4.15.0-112-generic linux-hwe-5.4-tools-5.4.0-40
  linux-image-4.15.0-112-generic linux-modules-4.15.0-112-generic linux-modules-extra-4.15.0-112-generic
Verwenden Sie »sudo apt autoremove«, um sie zu entfernen.
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 1 nicht aktualisiert.
oberstet@intel-nuci7:~$ egrep -c '(vmx|svm)' /proc/cpuinfo
8
oberstet@intel-nuci7:~$ kvm-ok
INFO: /dev/kvm exists
KVM acceleration can be used
oberstet@intel-nuci7:~$ sudo apt-get install qemu-kvm libvirt-bin ubuntu-vm-builder bridge-utils ia32-libs-multiarch
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
E: Paket ia32-libs-multiarch kann nicht gefunden werden.
oberstet@intel-nuci7:~$ sudo apt-get install qemu-kvm libvirt-bin ubuntu-vm-builder bridge-utils ia64-libs-multiarch
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
E: Paket ia64-libs-multiarch kann nicht gefunden werden.
oberstet@intel-nuci7:~$ 
```
