### ISSUE TITLE
WAMPCRA Password Salting

### ISSUE THREAD

**Issue by entone** [crossbario/autobahn-java#511]
It appears that password salting is not supported for the WAMPCRA authmethod.

Am I missing something?

**Comment by om26er** [comment]
That is true. But just looked at the code (again), I think it should be pretty straightforward to implement that. I might be able to implement that this week.

**Comment by entone** [comment]
That would be fantastic! Let me know if you need any support/testing whatever.

**Comment by om26er** [comment]
I have a work in progress pull request here https://github.com/crossbario/autobahn-java/pull/512 -- it is successfully able to derive the correct key (verified), however the signed challenge that we return gets rejected by Crossbar.
