### ISSUE TITLE
Maintain and publish a proper changelog

### ISSUE THREAD

**Issue by jpshelley** [crossbario/autobahn-java#66]
Should there be a new version of the jar on the docs page? It downloaded 0.5.0.jar for me but I noticed the TAGS show up to 0.5.2

It might be nice to add a CHANGELOG.md file to show what has been added in each subsequent version of the client.

This is a really nice project and would love to help out in anyway.

**Comment by oberstet** [comment]
I agree. there should be a changelog, and the docs published should clearly state what version of the library they document.

**Comment by om26er** [comment]
@oberstet Would messages from `git log` since last tag serve us good ?

example:
```
git log $(git describe --abbrev=0)..HEAD --pretty=format:"%s"
```
result:
```
Add config for maven publishing (#289)
Expose API for WS pings/pongs and implement auto keepalive (#287)
Reduce java8 usage internally (#285)
Make example client universal (#283)
Refactor WebSocket impl (#281)
Autobahn WAMP transport (#277)
Complete event retention support and add Event.topic property (#275)
```

**Comment by oberstet** [comment]
@om26er that would be much better than noting, and has basically zero overhead. With a little discipline on PR titles, that should really work.

How do I need to change above command to get output for complete history?

**Comment by om26er** [comment]
> How do I need to change above command to get output for complete history?

git log --pretty=format:"%s"

**Comment by oberstet** [comment]
ahh, right;) so your original command is printing out commit messages since last tagged version already. great. so yeah, we should go for this IMO - maybe add it as a make target?

**Comment by om26er** [comment]
I have proposed a change log generator here: https://github.com/crossbario/autobahn-java/pull/294 -- So in future the changelog will exist inside CHANGELOG.md

**Comment by om26er** [comment]
We now maintain a changelog and will ensure to do so every release. https://github.com/crossbario/autobahn-java/blob/master/CHANGELOG.md
