### ISSUE TITLE
Exception: sending message to a Handler on a dead thread

### ISSUE THREAD

**Issue by CrisVeli** [crossbario/autobahn-java#68]
10-07 10:53:27.659: W/MessageQueue(27516): Handler (de.tavendo.autobahn.WebSocketWriter) {42dbc630} sending message to a Handler on a dead thread
10-07 10:53:27.659: W/MessageQueue(27516): java.lang.RuntimeException: Handler (de.tavendo.autobahn.WebSocketWriter) {42dbc630} sending message to a Handler on a dead thread
10-07 10:53:27.659: W/MessageQueue(27516):  at android.os.MessageQueue.enqueueMessage(MessageQueue.java:320)
10-07 10:53:27.659: W/MessageQueue(27516):  at android.os.Handler.enqueueMessage(Handler.java:626)
10-07 10:53:27.659: W/MessageQueue(27516):  at android.os.Handler.sendMessageAtTime(Handler.java:595)
10-07 10:53:27.659: W/MessageQueue(27516):  at android.os.Handler.sendMessageDelayed(Handler.java:566)
10-07 10:53:27.659: W/MessageQueue(27516):  at android.os.Handler.sendMessage(Handler.java:503)
10-07 10:53:27.659: W/MessageQueue(27516):  at de.tavendo.autobahn.WebSocketWriter.forward(WebSocketWriter.java:102)
10-07 10:53:27.659: W/MessageQueue(27516):  at de.tavendo.autobahn.WebSocketConnection.failConnection(WebSocketConnection.java:181)
10-07 10:53:27.659: W/MessageQueue(27516):  at de.tavendo.autobahn.WebSocketConnection.access$1100(WebSocketConnection.java:34)
10-07 10:53:27.659: W/MessageQueue(27516):  at de.tavendo.autobahn.WebSocketConnection$2.handleMessage(WebSocketConnection.java:453)
10-07 10:53:27.659: W/MessageQueue(27516):  at android.os.Handler.dispatchMessage(Handler.java:102)
10-07 10:53:27.659: W/MessageQueue(27516):  at android.os.Looper.loop(Looper.java:157)
10-07 10:53:27.659: W/MessageQueue(27516):  at android.app.ActivityThread.main(ActivityThread.java:5356)
10-07 10:53:27.659: W/MessageQueue(27516):  at java.lang.reflect.Method.invokeNative(Native Method)
10-07 10:53:27.659: W/MessageQueue(27516):  at java.lang.reflect.Method.invoke(Method.java:515)
10-07 10:53:27.659: W/MessageQueue(27516):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
10-07 10:53:27.659: W/MessageQueue(27516):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
10-07 10:53:27.659: W/MessageQueue(27516):  at dalvik.system.NativeStart.main(Native Method)

**Comment by pizza** [comment]
I am seeing this issue too

**Comment by snowbreeze** [comment]
I see this too

**Comment by laukamp** [comment]
I see this too

**Comment by arashmidos** [comment]
@CrisVeli how should I set that config? Is it working woth 0.5.0 version?

**Comment by BackPackerDz** [comment]
I see this too

**Comment by ray0807** [comment]
I see this too

**Comment by ouyangzn** [comment]
I see this many times

**Comment by PhilLab** [comment]
:+1:

**Comment by WhatTheCode** [comment]
I see this too

**Comment by smithaaron** [comment]
Me too.

**Comment by Thomas-Valloo** [comment]
+1

**Comment by AnthonyKoueik** [comment]
did anyone solve it ?

**Comment by om26er** [comment]
I am working on it, we should have something soon, though that will land in abjv2 branch for now.

**Comment by om26er** [comment]
This issue is fixed in master. If anyone sees it with master then it should probably be dealt on case by case bases. We can close this now.
