### ISSUE TITLE
WebSocketReader: run(): WebSocketException (WebSocketException: RSV != 0 and no extension negotiated)

### ISSUE THREAD

**Issue by hamdarsi** [crossbario/autobahn-java#79]
I'm trying to run RPC demo of autobahn. Running the demo will result in this output:

`04-14 15:52:06.024  11044-11284/de.tavendo.autobahn.simplerpc D/de.tavendo.autobahn.WebSocketReader﹕ created
04-14 15:52:06.064  11044-11284/de.tavendo.autobahn.simplerpc D/de.tavendo.autobahn.WampReader﹕ created
04-14 15:52:06.064  11044-11284/de.tavendo.autobahn.simplerpc D/de.tavendo.autobahn.WampConnection﹕ reader created and started
04-14 15:52:06.065  11044-11285/de.tavendo.autobahn.simplerpc D/de.tavendo.autobahn.WebSocketReader﹕ running
04-14 15:52:06.068  11044-11284/de.tavendo.autobahn.simplerpc D/de.tavendo.autobahn.WebSocketWriter﹕ created
04-14 15:52:06.068  11044-11284/de.tavendo.autobahn.simplerpc D/de.tavendo.autobahn.WampWriter﹕ created
04-14 15:52:06.068  11044-11284/de.tavendo.autobahn.simplerpc D/de.tavendo.autobahn.WampConnection﹕ writer created and started
04-14 15:52:06.079  11044-11285/de.tavendo.autobahn.simplerpc W/de.tavendo.autobahn.WebSocketReader﹕ Status: 200 (OK)
04-14 15:52:06.080  11044-11285/de.tavendo.autobahn.simplerpc D/de.tavendo.autobahn.WebSocketReader﹕ run() : WebSocketException (de.tavendo.autobahn.WebSocketException: RSV != 0 and no extension negotiated)
04-14 15:52:06.080  11044-11285/de.tavendo.autobahn.simplerpc D/de.tavendo.autobahn.WebSocketReader﹕ ended`

I traced the code to the point where `WebSocketReader.processData()` throws the mentioned exception. 

My guess: The router which I'm trying to connect to is current version of crossbar and I know that Autobahn/Android can not use version 2 features of WAMP. Is this exception related to the version mismatch? If it is related, should I do something like degrade crossbar to V1?

**Comment by lablancas** [comment]
I was having the same problem so I tested websocket support with this site. 
https://www.websocket.org/echo.html

Ws didn't work but wss did so I think I will be adding ssl support to my client and server

**Comment by oberstet** [comment]
> My guess: The router which I'm trying to connect to is current version of crossbar and I know that Autobahn/Android can not use version 2 features of WAMP. Is this exception related to the version mismatch? If it is related, should I do something like degrade crossbar to V1?

AutobahnAndroid right now only speaks WAMPv1, and Crossbar.io only speaks WAMPv2. Upgrading the former will be addressed as part of https://github.com/crossbario/autobahn-android/issues/92

However, AutobahnAndroid (even now) should not bail out with above .. Crossbar.io will only speak extensions (like permessage-deflate) if properly negotiated. This might hence be a bug in the WebSocket implementation of AutobahnAndroid .. and hence I leave it open for investigation.

**Comment by oberstet** [comment]
this library now implements WAMP v2
